/**
 * GESP 一级 C++ 题库
 * 包含 8 个知识点练习题 + 模拟考试 + 真题回放
 * 总计 233 题
 */
const QUESTION_BANK = {
  meta: {
    name: "GESP 一级 C++",
    version: "2.0",
    totalQuestions: 233,
    knowledgePoints: {
      kp01: { title: "变量与数据类型", questions: 15 },
      kp02: { title: "基本运算", questions: 15 },
      kp03: { title: "输入输出", questions: 15 },
      kp04: { title: "条件语句", questions: 15 },
      kp05: { title: "循环语句", questions: 15 },
      kp06: { title: "数组基础", questions: 15 },
      kp07: { title: "字符与字符串", questions: 15 },
      kp08: { title: "函数基础", questions: 15 }
    },
    mockExamQuestions: 30,
    realExamQuestions: 20
  },

  knowledgePoints: {
    kp01: {
      title: "变量与数据类型",
      subtitle: "掌握 C++ 基本数据类型、变量声明与初始化",
      theory: '<h4>1. 基本数据类型</h4>\n<ul>\n  <li><code>int</code> 整型，通常 4 字节，范围约 -21 亿 ~ 21 亿</li>\n  <li><code>float</code> 单精度浮点数，4 字节，约 7 位有效数字</li>\n  <li><code>double</code> 双精度浮点数，8 字节，约 15 位有效数字</li>\n  <li><code>char</code> 字符型，1 字节，存储 ASCII 字符</li>\n  <li><code>bool</code> 布尔型，true 或 false</li>\n</ul>\n<h4>2. 变量声明与初始化</h4>\n<pre>int age = 15;\ndouble pi = 3.14;\nchar grade = \'A\';\nbool isStudent = true;</pre>\n<h4>3. sizeof 运算符</h4>\n<p>使用 <code>sizeof(类型)</code> 可以查看类型所占字节数。</p>\n<pre>cout &lt;&lt; sizeof(int) &lt;&lt; endl;    // 输出 4\ncout &lt;&lt; sizeof(double) &lt;&lt; endl;  // 输出 8\ncout &lt;&lt; sizeof(char) &lt;&lt; endl;   // 输出 1</pre>\n<h4>4. 易错点</h4>\n<p class="warn">⚠ 变量未初始化就使用，值是不确定的（未定义行为）</p>\n<p class="warn">⚠ int 和 double 混用时注意自动类型转换</p>\n<p class="warn">⚠ char 用单引号 <code>\'A\'</code>，string 用双引号 <code>"A"</code></p>',
      questions: [
        { id: "kp01_q01", type: "choice", difficulty: 1, question: "在 C++ 中，以下哪个关键字用于声明整型变量？", options: ["float", "int", "char", "bool"], answer: 1, explanation: "int 是 C++ 中用于声明整型变量的关键字。float 用于浮点数，char 用于字符，bool 用于布尔值。" },
        { id: "kp01_q02", type: "choice", difficulty: 1, question: "以下哪个是合法的 C++ 变量名？", options: ["2name", "my_var", "class", "my-var"], answer: 1, explanation: "变量名不能以数字开头（排除 A），不能是关键字（排除 C），不能包含连字符（排除 D）。my_var 使用下划线，是合法的变量名。" },
        { id: "kp01_q03", type: "choice", difficulty: 1, question: "sizeof(double) 的值是多少？", options: ["1", "2", "4", "8"], answer: 3, explanation: "double 是双精度浮点数，在大多数系统中占 8 个字节。float 占 4 字节，int 通常占 4 字节，char 占 1 字节。" },
        { id: "kp01_q04", type: "choice", difficulty: 2, question: "以下代码的输出是什么？\n<pre><code>int a = 5;\nint b = 2;\ndouble c = a / b;\ncout &lt;&lt; c;</code></pre>", options: ["2.5", "2", "2.0", "编译错误"], answer: 1, explanation: "a / b 是两个 int 相除，结果为整数 2（截断小数部分）。虽然 c 是 double 类型，但赋值时已经是 2.0，输出为 2。" },
        { id: "kp01_q05", type: "choice", difficulty: 2, question: "关于 bool 类型，以下哪个说法是正确的？", options: ["bool 变量只能存储 0 或 1", "bool 变量存储 true 或 false，true 等价于非零值", "bool 类型占用 4 字节内存", "bool 类型不能用于条件判断"], answer: 1, explanation: "bool 类型存储 true 或 false。在内部，true 通常等价于 1（非零值），false 等价于 0。bool 通常只占 1 字节。" },
        { id: "kp01_q06", type: "choice", difficulty: 2, question: "以下哪种初始化方式是错误的？", options: ["int x = 10;", "int x(10);", "int x{10};", "int x = = 10;"], answer: 3, explanation: "A 是拷贝初始化，B 是直接初始化，C 是列表初始化（C++11），都是合法的。D 的 = = 是语法错误。" },
        { id: "kp01_q07", type: "choice", difficulty: 2, question: "以下C++不可以作为变量的名称的是（ ）。", options: ["CCF GESP", "ccfGESP", "CCFgesp", "CCF_GESP"], answer: 0, explanation: "C++ 变量名中不能包含空格。A 选项含有空格，无法作为变量名。", source: "2023_12" },
        { id: "kp01_q08", type: "choice", difficulty: 2, question: "定义变量char c，下面对c赋值的语句，不符合语法的是( )。", options: ["c = (char)66;", "c = (char)(66);", "c = char(66);", "c = char 66;"], answer: 3, explanation: "A、B 是 C 风格类型转换，C 是函数式类型转换，都合法。D 的 \"char 66\" 不是合法的类型转换语法。", source: "2023_12" },
        { id: "kp01_q09", type: "choice", difficulty: 2, question: "执行以下代码后，a 和 b 的值分别是？\n<pre><code>int a = 3.7;\nchar b = 66;</code></pre>", options: ["a=3.7, b=B", "a=4, b=66", "a=3, b=B", "编译错误"], answer: 2, explanation: "int a = 3.7 会截断小数部分，a 的值为 3。char b = 66，ASCII 码 66 对应字符 'B'。" },
        { id: "kp01_q10", type: "choice", difficulty: 3, question: "下面关于整型变量int x的赋值语句不正确是( )。", options: ["x=(3.16);", "x=3.16;", "x=int(3.16);", "x=3.16 int;"], answer: 3, explanation: "A、B 赋值3.16给int隐式截断为3；C 显式转换。D 语法错误。", source: "2024_03" },
        { id: "kp01_q11", type: "choice", difficulty: 1, question: "在C++中，下列可以做变量的是( )。", options: ["Var-1", "$1", "%%1", "_Var_1"], answer: 3, explanation: "变量名不能包含连字符(-)、不能以$开头、不能包含%%。_Var_1 合法。", source: "2025_03" },
        { id: "kp01_q12", type: "choice", difficulty: 2, question: "以下哪个是C++语言的关键字？（ ）", options: ["abs", "cin", "do", "endl"], answer: 2, explanation: "do 是 C++ 的关键字（用于 do-while 循环）。abs 是函数名，cin 是标准输入对象，endl 是输出操纵符。", source: "2025_03" },
        { id: "kp01_q13", type: "choice", difficulty: 2, question: "C++语言中3.0和3的值相等，所以它们占用的存储空间也相同。（ ）", options: ["正确", "错误"], answer: 1, explanation: "3.0 是 double 类型占 8 字节，3 是 int 类型占 4 字节。值相等但类型不同，存储空间不同。", source: "2024_03", isJudge: true },
        { id: "kp01_q14", type: "coding", difficulty: 2, question: "编写程序，分别声明 int、double、char、bool 类型的变量并输出它们各自占多少字节。\n<p>提示：使用 <code>sizeof()</code> 运算符。</p>\n<p>预期输出格式（每行一个数字）：</p>\n<pre><code>4\n8\n1\n1</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    // 声明四种类型的变量\n    \n    // 分别输出每种类型占的字节数\n    \n    return 0;\n}", testCases: [{ input: "", expectedOutput: "4\n8\n1\n1", description: "依次输出 int, double, char, bool 的字节数" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a;\n    double b;\n    char c;\n    bool d;\n    cout << sizeof(a) << endl;\n    cout << sizeof(b) << endl;\n    cout << sizeof(c) << endl;\n    cout << sizeof(d) << endl;\n    return 0;\n}", explanation: "使用 sizeof() 可以获取变量占用的字节数。int 通常 4 字节，double 8 字节，char 1 字节，bool 1 字节。" },
        { id: "kp01_q15", type: "coding", difficulty: 2, question: "编写程序，声明两个 int 变量 a=10, b=3，然后输出它们的和、差、积、商（整数除法）和余数。\n<p>预期输出：</p>\n<pre><code>13\n7\n30\n3\n1</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a = 10, b = 3;\n    \n    // 输出和、差、积、商、余数\n    \n    return 0;\n}", testCases: [{ input: "", expectedOutput: "13\n7\n30\n3\n1", description: "和=13, 差=7, 积=30, 商=3, 余数=1" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a = 10, b = 3;\n    cout << a + b << endl;\n    cout << a - b << endl;\n    cout << a * b << endl;\n    cout << a / b << endl;\n    cout << a % b << endl;\n    return 0;\n}", explanation: "整数除法 a/b 会截断小数部分得到 3，取余 a%b 得到 1。" }
      ]
    },

    kp02: {
      title: "基本运算",
      subtitle: "掌握算术、比较、逻辑运算符与运算符优先级",
      theory: '<h4>1. 算术运算符</h4>\n<ul>\n  <li><code>+</code> 加法、<code>-</code> 减法、<code>*</code> 乘法、<code>/</code> 除法、<code>%</code> 取余</li>\n  <li>两个整数相除结果为整数：<code>7 / 2</code> = <code>3</code></li>\n  <li><code>%</code> 取余运算符只能用于整数：<code>10 % 3</code> = <code>1</code></li>\n</ul>\n<h4>2. 比较运算符</h4>\n<ul>\n  <li><code>==</code> 等于、<code>!=</code> 不等于、<code>&lt;</code> <code>&gt;</code> <code>&lt;=</code> <code>&gt;=</code></li>\n  <li>比较结果是 bool 值（true 或 false）</li>\n</ul>\n<h4>3. 逻辑运算符</h4>\n<ul>\n  <li><code>&amp;&amp;</code> 逻辑与：两边都为 true 才为 true</li>\n  <li><code>||</code> 逻辑或：一边为 true 就为 true</li>\n  <li><code>!</code> 逻辑非：取反</li>\n</ul>\n<h4>4. 运算符优先级（高→低）</h4>\n<pre>! → * / % → + - → 比较 → == != → &amp;&amp; → || → 赋值</pre>\n<p class="warn">⚠ 使用括号可以改变优先级并提高可读性</p>',
      questions: [
        { id: "kp02_q01", type: "choice", difficulty: 1, question: "表达式 <code>3 + 4 * 5</code> 的值是多少？", options: ["35", "23", "20", "27"], answer: 1, explanation: "乘法优先级高于加法，先算 4*5=20，再算 3+20=23。" },
        { id: "kp02_q02", type: "choice", difficulty: 1, question: "在 C++ 中，整数除法 <code>7 / 2</code> 的结果是？", options: ["3.5", "3", "4", "3.0"], answer: 1, explanation: "两个整数相除结果仍为整数，小数部分被截断。7 / 2 = 3。" },
        { id: "kp02_q03", type: "choice", difficulty: 1, question: "<code>10 % 3</code> 的结果是？", options: ["3", "1", "0", "3.33"], answer: 1, explanation: "% 是取余运算符，10 ÷ 3 = 3 余 1，所以 10 % 3 = 1。" },
        { id: "kp02_q04", type: "choice", difficulty: 2, question: "以下哪个表达式的结果是 <code>true</code>？\n<pre><code>bool a = true;\nbool b = false;</code></pre>", options: ["a &amp;&amp; b", "a || b", "!a", "b && !b"], answer: 1, explanation: "a || b = true || false = true。逻辑或只要有一边为 true 就返回 true。" },
        { id: "kp02_q05", type: "choice", difficulty: 2, question: "执行以下代码后，x 的值是？\n<pre><code>int x = 10;\nx += 5;\nx -= 3;</code></pre>", options: ["12", "15", "10", "8"], answer: 0, explanation: "x += 5 使 x 变为 15，x -= 3 使 x 变为 12。" },
        { id: "kp02_q06", type: "choice", difficulty: 2, question: "C++表达式10 - 3 * (2 + 1) % 10的值是( )。", options: ["0", "1", "2", "3"], answer: 1, explanation: "先算括号(2+1)=3，再算乘法 3*3=9，取余 9%10=9，最后 10-9=1。", source: "2023_12" },
        { id: "kp02_q07", type: "choice", difficulty: 2, question: "表达式3 - 3 * 3 / 5的值是( )。", options: ["-1.2", "1", "0", "2"], answer: 3, explanation: "先算乘除：3*3=9, 9/5=1（整数除法），再算 3-1=2。", source: "2024_06" },
        { id: "kp02_q08", type: "choice", difficulty: 2, question: "C++表达式16 / 4 % 2的值是( )。", options: ["8", "4", "2", "0"], answer: 3, explanation: "先算除法 16/4=4，再算取余 4%2=0。", source: "2025_03" },
        { id: "kp02_q09", type: "choice", difficulty: 2, question: "N=12，则cout << (N % 3 + N / 5)的输出是( )。", options: ["6.4", "2.4", "6", "2"], answer: 3, explanation: "N%3=12%3=0，N/5=12/5=2（整数除法），0+2=2。", source: "2025_03" },
        { id: "kp02_q10", type: "choice", difficulty: 3, question: "表达式9/4 - 6 % (6 - 2) * 10的值是( )。", options: ["-17.75", "-18", "-14", "-12.75"], answer: 1, explanation: "先算括号(6-2)=4，再算 9/4=2, 6%4=2, 2*10=20，最后 2-20=-18。", source: "2024_06" },
        { id: "kp02_q11", type: "choice", difficulty: 2, question: "C++表达式(6 > 2) * 2的值是( )。", options: ["1", "2", "true", "truetrue"], answer: 1, explanation: "(6>2) 结果为 true（值为1），1*2=2。", source: "2024_12" },
        { id: "kp02_q12", type: "choice", difficulty: 2, question: "在C++中，假设N为正整数，则cout << (N % 3 + N % 7)可能输出的最大值是( )。", options: ["6", "8", "9", "10"], answer: 1, explanation: "N%3最大为2，N%7最大为6，所以最大为2+6=8。", source: "2024_06" },
        { id: "kp02_q13", type: "choice", difficulty: 3, question: "C++表达式010+100+001的值为111。（ ）", options: ["正确", "错误"], answer: 1, explanation: "010和001是八进制数，010=8, 001=1，所以 8+100+1=109，不是111。", source: "2023_12", isJudge: true },
        { id: "kp02_q14", type: "coding", difficulty: 2, question: "给定圆的半径 r = 5，计算并输出圆的面积（取 π = 3.14）。\n<p>公式：面积 = π × r × r</p>\n<p>预期输出：</p>\n<pre><code>78.5</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int r = 5;\n    // 计算圆的面积\n    \n    // 输出结果\n    \n    return 0;\n}", testCases: [{ input: "", expectedOutput: "78.5", description: "半径为5的圆面积" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int r = 5;\n    double area = 3.14 * r * r;\n    cout << area << endl;\n    return 0;\n}", explanation: "使用公式 area = 3.14 * r * r。注意要用 double 类型。" },
        { id: "kp02_q15", type: "coding", difficulty: 2, question: "给定摄氏温度 C=100，使用公式 F = C * 9 / 5 + 32 转换为华氏温度并输出。\n<p>预期输出：</p>\n<pre><code>212</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int C = 100;\n    // 转换为华氏温度\n    \n    // 输出结果\n    \n    return 0;\n}", testCases: [{ input: "", expectedOutput: "212", description: "100度摄氏转华氏" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int C = 100;\n    double F = C * 9.0 / 5 + 32;\n    cout << F << endl;\n    return 0;\n}", explanation: "使用公式 F = C * 9.0 / 5 + 32。注意乘以 9.0 确保浮点除法。" }
      ]
    },

    kp03: {
      title: "输入输出",
      subtitle: "掌握 cout/cin 与 printf/scanf 格式化输入输出",
      theory: '<h4>1. 基本输出 cout</h4>\n<ul>\n  <li><code>cout &lt;&lt; 内容</code> 输出到屏幕</li>\n  <li><code>&lt;&lt;</code> 可以连续使用（链式输出）</li>\n  <li>换行用 <code>endl</code> 或 <code>"\\n"</code></li>\n</ul>\n<h4>2. endl 与 "\\n"</h4>\n<ul>\n  <li><code>endl</code>：换行并刷新缓冲区</li>\n  <li><code>"\\n"</code>：只换行不刷新，效率更高</li>\n</ul>\n<h4>3. 基本输入 cin</h4>\n<ul>\n  <li><code>cin &gt;&gt; 变量</code> 从键盘读取</li>\n  <li>多个值以空格、Tab 或换行分隔</li>\n</ul>\n<h4>4. printf / scanf（C 风格）</h4>\n<pre>printf("整数=%d, 浮点=%.2f\\n", n, f);\nscanf("%d", &amp;n);</pre>\n<p class="warn">⚠ printf 中 % 是格式说明符，输出 % 需写 %%</p>',
      questions: [
        { id: "kp03_q01", type: "choice", difficulty: 1, question: "以下哪种方式可以正确输出 \"Hello\" 后换行？", options: ["cout >> \"Hello\" >> endl;", "cout << \"Hello\" << endl;", "cin << \"Hello\" << endl;", "cout << \"Hello\" >> endl;"], answer: 1, explanation: "cout 使用 << 插入运算符，endl 也通过 << 插入。>> 用于输入。" },
        { id: "kp03_q02", type: "choice", difficulty: 1, question: "endl 和 \"\\n\" 的主要区别是什么？", options: ["没有任何区别", "endl 会刷新缓冲区，\"\\n\" 不会", "\\n 会刷新缓冲区", "endl 输出两个换行"], answer: 1, explanation: "endl 除了换行还会刷新缓冲区，\"\\n\" 只换行不刷新。" },
        { id: "kp03_q03", type: "choice", difficulty: 2, question: "C++语句printf(\"5%%2={%d}\\n\",5 % 2)执行后的输出是( )。", options: ["1={1}", "5%2={5%2}", "5%2={1}", "5 ={1}"], answer: 2, explanation: "printf 中 %% 输出一个 %，%d 格式化整数5%2=1，所以输出 \"5%2={1}\"。", source: "2024_06" },
        { id: "kp03_q04", type: "choice", difficulty: 2, question: "下面C++代码执行后的输出是（ ）。\n<pre><code>int a = 1;\ncout << \"a+1= \" << a+1 << endl;</code></pre>", options: ["a+1= 2", "a+1=2", "2=2", "2= 2"], answer: 0, explanation: "cout 原样输出字符串 \"a+1= \"（等号后有空格），然后输出 a+1=2。", source: "2024_03" },
        { id: "kp03_q05", type: "choice", difficulty: 2, question: "下面C++代码执行后的输出是（ ）。\n<pre><code>int a = 1;\nprintf(\"a+1=%d\\n\", a+1);</code></pre>", options: ["a+1= 2", "a+1=2", "2=2", "2= 2"], answer: 1, explanation: "printf 中 %d 替换为 a+1 的值 2，格式串中 = 后没有空格。", source: "2024_03" },
        { id: "kp03_q06", type: "choice", difficulty: 2, question: "执行cin >> i, cout << i时如果输入5+2，输出是（ ）。", options: ["整数7", "5", "报错", "内容不确定"], answer: 1, explanation: "cin 读取整数遇到非数字(+)就停止，i=5，输出5。", source: "2024_06" },
        { id: "kp03_q07", type: "choice", difficulty: 2, question: "先后输入100和200后，cout << (first / second * second) 的输出是（ ）。", options: ["200", "100", "1", "0"], answer: 3, explanation: "100/200=0（整数除法），0*200=0。", source: "2025_03" },
        { id: "kp03_q08", type: "choice", difficulty: 2, question: "C++语言中下面可以完成数据输入的语句是（ ）。", options: ["printf语句", "scanf语句", "default语句", "cout语句"], answer: 1, explanation: "scanf 用于格式化输入。printf 和 cout 用于输出。", source: "2024_03" },
        { id: "kp03_q09", type: "choice", difficulty: 3, question: "下面C++语句（ ）执行后的输出是__ 0322$$。", options: ["printf(\"__ %2d%02d$$\", 3, 22)", "printf(\"__ %02d%2d$$\", 3, 22)", "printf(\"__ %02d%02d$$$$\", 3, 22)", "printf(\"____ %02d%02d$$$$\", 3, 22)"], answer: 1, explanation: "%02d不足补0得\"03\"，%2d不足补空格得\"22\"，所以 __ 0322$$。", source: "2025_03" },
        { id: "kp03_q10", type: "choice", difficulty: 2, question: "下面C++代码执行后的输出是( )。\n<pre><code>int N = 10;\nprintf(\"{N}*{N}={%d*%d}\", N, N, N * N);</code></pre>", options: ["10*10={10*10}", "100=10", "N*N=100", "{N}*{N}={10*10}"], answer: 3, explanation: "printf 中 {} 不是格式说明符原样输出。%d 替换为10和100。", source: "2025_03" },
        { id: "kp03_q11", type: "choice", difficulty: 2, question: "下面C++代码的说法，错误的是( )。\n<pre><code>printf(\"我爱码代码！\");</code></pre>", options: ["汉字改为Hello代码能正确执行", "汉字改为Hello代码！能正确执行", "双引号都可以改为两个单引号", "双引号都可以改为三个双引号"], answer: 2, explanation: "两个单引号表示 char 字符，不能替代双引号表示字符串。", source: "2025_03" },
        { id: "kp03_q12", type: "choice", difficulty: 2, question: "下面C++代码执行后输出是（ ）。\n<pre><code>float a;\na = 101.101;\na = 101;\nprintf(\"a+1={%.0f}\",a+1);</code></pre>", options: ["102={102}", "a+1={a+1}", "a+1={102}", "a先被赋值为浮点数，后被赋值为整数，执行将报错"], answer: 2, explanation: "a是float可以赋值整数，%.0f不输出小数部分，所以 a+1=102。", source: "2024_06" },
        { id: "kp03_q13", type: "choice", difficulty: 1, question: "C++函数scanf()必须含有参数，且其参数为字符串型字面量，其功能是提示输入。（ ）", options: ["正确", "错误"], answer: 1, explanation: "scanf 的参数是格式字符串，功能是格式化读取输入，不是提示输入。提示输入是 printf 的功能。", source: "2024_03", isJudge: true },
        { id: "kp03_q14", type: "coding", difficulty: 1, question: "编写程序，从标准输入读入两个整数，输出它们的和。\n<p>测试输入：<code>3 5</code></p>\n<p>预期输出：</p>\n<pre><code>8</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    // 读入两个整数\n    \n    // 输出它们的和\n    \n    return 0;\n}", testCases: [{ input: "3 5", expectedOutput: "8", description: "3 + 5 = 8" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a + b << endl;\n    return 0;\n}", explanation: "使用 cin >> a >> b 读入，cout 输出 a + b。" },
        { id: "kp03_q15", type: "coding", difficulty: 2, question: "编写程序，读入两个整数，输出 \"a + b = sum\"。\n<p>测试输入：<code>3 7</code></p>\n<p>预期输出：</p>\n<pre><code>3 + 7 = 10</code></pre>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    // 按格式输出\n    \n    return 0;\n}", testCases: [{ input: "3 7", expectedOutput: "3 + 7 = 10", description: "格式化输出加法" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a << \" + \" << b << \" = \" << a + b << endl;\n    return 0;\n}", explanation: "使用链式输出依次输出各部分。" }
      ]
    },

    kp04: {
      title: "条件语句",
      subtitle: "掌握 if、if-else、if-else if-else 与三目运算符",
      theory: '<h4>1. if 语句</h4>\n<pre>if (条件) {\n    // 条件为 true 时执行\n}</pre>\n<h4>2. if-else 语句</h4>\n<pre>if (条件) {\n    // true 时执行\n} else {\n    // false 时执行\n}</pre>\n<h4>3. if-else if-else 多分支</h4>\n<pre>if (条件1) {\n    // ...\n} else if (条件2) {\n    // ...\n} else {\n    // 以上都不满足\n}</pre>\n<h4>4. 三目运算符</h4>\n<pre>结果 = 条件 ? 值1 : 值2;</pre>\n<h4>5. 常见错误</h4>\n<p class="warn">⚠ <code>=</code> 是赋值，<code>==</code> 才是比较！</p>\n<p class="warn">⚠ if 后面不要加分号</p>\n<p class="warn">⚠ else 匹配最近的未匹配 if</p>',
      questions: [
        { id: "kp04_q01", type: "choice", difficulty: 1, question: "以下代码执行后，变量 x 的值是多少？\n<pre><code>int x = 0;\nif (5 > 3)\n    x = 10;</code></pre>", options: ["0", "10", "5", "编译错误"], answer: 1, explanation: "5 > 3 为 true，执行 x = 10，x 最终为 10。" },
        { id: "kp04_q02", type: "choice", difficulty: 1, question: "以下代码的输出是什么？\n<pre><code>int a = 3, b = 5;\nif (a > b) cout << \"A\";\nelse cout << \"B\";</code></pre>", options: ["A", "B", "AB", "编译错误"], answer: 1, explanation: "a=3, b=5，a > b 为 false，执行 else 输出 B。" },
        { id: "kp04_q03", type: "choice", difficulty: 2, question: "以下代码执行后，count 的值是多少？\n<pre><code>int count = 0, x = 5;\nif (x > 3) count++;\nif (x > 4) count++;\nif (x > 5) count++;</code></pre>", options: ["0", "1", "2", "3"], answer: 2, explanation: "x=5：5>3(true,count=1)，5>4(true,count=2)，5>5(false)。count=2。" },
        { id: "kp04_q04", type: "choice", difficulty: 2, question: "以下代码中，else 匹配哪个 if？\n<pre><code>if (a > 0)\n    if (b > 0)\n        cout << \"1\";\nelse\n    cout << \"2\";</code></pre>", options: ["外层 if", "内层 if", "两个都匹配", "编译错误"], answer: 1, explanation: "else 匹配最近的未匹配 if，即内层的 if (b > 0)。" },
        { id: "kp04_q05", type: "choice", difficulty: 2, question: "执行以下代码后，输出是什么？\n<pre><code>int x = 3;\nif (x > 2 && x < 5)\n    cout << \"Yes\";\nelse\n    cout << \"No\";</code></pre>", options: ["Yes", "No", "YesNo", "编译错误"], answer: 0, explanation: "3>2 && 3<5 都为 true，输出 Yes。" },
        { id: "kp04_q06", type: "choice", difficulty: 3, question: "执行以下代码后输出？\n<pre><code>int a = 10, b = 20;\nint max = (a > b) ? a : b;\ncout << max;</code></pre>", options: ["10", "20", "30", "编译错误"], answer: 1, explanation: "三目运算符：10>20 为 false，取 b=20。" },
        { id: "kp04_q07", type: "choice", difficulty: 2, question: "if语句中的条件表达式的结果可以为int类型。（ ）", options: ["正确", "错误"], answer: 0, explanation: "C++ 中非零值视为 true，零视为 false。", source: "2023_12", isJudge: true },
        { id: "kp04_q08", type: "choice", difficulty: 2, question: "下面C++代码输入14后输出是（ ）。\n<pre><code>int P;\nscanf(\"%d\", &P);\nif (P % 3 || P % 7)\n    printf(\"第5行%d, %d\", P % 3, P % 7);\nelse\n    printf(\"第7行%2d\", P % 3 && P % 7);</code></pre>", options: ["第5行代码2, 0", "第5行代码1, 0", "第7行代码 1", "第7行代码 0"], answer: 0, explanation: "P=14，14%3=2(非零), 14%7=0。2||0=2(真)，输出 \"第5行代码2, 0\"。", source: "2024_09" },
        { id: "kp04_q09", type: "choice", difficulty: 2, question: "判断N是否为能被3整除的偶数，横线处应填（ ）。\n<pre><code>if(_______) cout << \"能被3整除的偶数\";</code></pre>", options: ["(N%2)&&(N%3)", "(N%2==0)&&(N%3)", "(N%2)&&(N%3==0)", "(N%2==0)&&(N%3==0)"], answer: 3, explanation: "能被2整除 N%2==0，能被3整除 N%3==0，都要满足用 &&。", source: "2024_12" },
        { id: "kp04_q10", type: "choice", difficulty: 2, question: "输入21后，下面代码输出是（ ）。\n<pre><code>if(N%3 == 0) cout << \"能被3整除\";\nelse if (N % 7 == 0) cout << \"能被7整除\";\nelse cout << \"不能被3和7整除\";</code></pre>", options: ["能被3整除", "能被3整除和能被7整除", "能被7整除", "不能被3和7整除"], answer: 0, explanation: "21%3==0为true，输出\"能被3整除\"后跳过else分支。", source: "2024_03" },
        { id: "kp04_q11", type: "choice", difficulty: 2, question: "C++中break适用于while循环但不适用于for循环。（ ）", options: ["正确", "错误"], answer: 1, explanation: "break 同时适用于 for、while 和 do-while 循环。", source: "2024_03", isJudge: true },
        { id: "kp04_q12", type: "choice", difficulty: 2, question: "while可能是死循环，而for循环不可能是死循环。（ ）", options: ["正确", "错误"], answer: 1, explanation: "for 循环也可以是死循环，如 for(;;) 或 for(int i=0; i<10; )。", source: "2024_03", isJudge: true },
        { id: "kp04_q13", type: "choice", difficulty: 2, question: "下面C++代码执行后，判断输入的整数N是否为位增数（从首位到个位逐渐增大）。若N=123输出1。（ ）\n<pre><code>cin >> N;\n_______;\nwhile(N){\n    n1 = N % 10;\n    if(n1 >= n2) { cout << 0; return 1; }\n    n2 = n1, N /=10;\n}\ncout << 1;</code></pre>", options: ["n2 = N%10", "N /= 10", "n2 = N/10, N %= 10", "n2 = N%10, N /= 10"], answer: 3, explanation: "需要先取个位赋给n2，然后去掉个位(N/=10)，这样循环中可以逐位比较。", source: "2024_12" },
        { id: "kp04_q14", type: "coding", difficulty: 1, question: "编写程序，读入一个整数，大于0输出\"正数\"，小于0输出\"负数\"，等于0输出\"零\"。\n<p>测试输入：<code>-5</code></p>\n<p>预期输出：<code>负数</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // 判断正负零\n    \n    return 0;\n}", testCases: [{ input: "-5", expectedOutput: "负数", description: "输入-5输出负数" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    if (n > 0) cout << \"正数\" << endl;\n    else if (n < 0) cout << \"负数\" << endl;\n    else cout << \"零\" << endl;\n    return 0;\n}", explanation: "使用 if-else if-else 依次判断。" },
        { id: "kp04_q15", type: "coding", difficulty: 2, question: "编写程序，读入三个整数，输出最大的一个。\n<p>测试输入：<code>3 7 5</code></p>\n<p>预期输出：<code>7</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    // 求最大值\n    \n    return 0;\n}", testCases: [{ input: "3 7 5", expectedOutput: "7", description: "最大值为7" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    int max = a;\n    if (b > max) max = b;\n    if (c > max) max = c;\n    cout << max << endl;\n    return 0;\n}", explanation: "假设 a 最大，逐一比较更新。" }
      ]
    },

    kp05: {
      title: "循环语句",
      subtitle: "掌握 for、while、do-while 与 break/continue",
      theory: '<h4>1. for 循环</h4>\n<pre>for (int i = 0; i < 10; i++) {\n    // 循环体\n}</pre>\n<h4>2. while 循环</h4>\n<pre>while (条件) {\n    // 条件为 true 时执行\n}</pre>\n<h4>3. do-while 循环</h4>\n<pre>do {\n    // 至少执行一次\n} while (条件);</pre>\n<h4>4. break 和 continue</h4>\n<ul>\n  <li><code>break</code>：跳出当前循环</li>\n  <li><code>continue</code>：跳过本次，进入下一次</li>\n</ul>',
      questions: [
        { id: "kp05_q01", type: "choice", difficulty: 1, question: "以下哪种循环适合已知循环次数？", options: ["while", "do-while", "for", "三种都一样"], answer: 2, explanation: "for 循环将初始化、条件、更新集中在一行，最适合已知次数。" },
        { id: "kp05_q02", type: "choice", difficulty: 1, question: "以下代码的输出是什么？\n<pre><code>int i = 1;\ndo {\n    cout << i << \" \";\n    i++;\n} while (i > 5);</code></pre>", options: ["无输出", "1", "1 2 3 4 5", "编译错误"], answer: 1, explanation: "do-while 至少执行一次，输出1后i=2，2>5 为 false 退出。" },
        { id: "kp05_q03", type: "choice", difficulty: 2, question: "以下代码输出什么？\n<pre><code>for (int i = 1; i <= 5; i++) {\n    if (i == 2) continue;\n    if (i == 4) break;\n    cout << i << \" \";\n}</code></pre>", options: ["1 3 5", "1 2 3", "1 3", "1 2 3 4"], answer: 2, explanation: "i=1输出1，i=2跳过，i=3输出3，i=4跳出。输出\"1 3\"。" },
        { id: "kp05_q04", type: "choice", difficulty: 2, question: "以下哪个会导致无限循环？", options: ["for(int i=0;i<10;i++){}", "int i=0; while(i<10){i++;}", "int i=0; while(i<10){cout<<i;}", "int i=0; do{i++;}while(i<10);"], answer: 2, explanation: "选项C中 i 从未被修改，条件始终为 true。" },
        { id: "kp05_q05", type: "choice", difficulty: 2, question: "嵌套循环内层循环体执行几次？\n<pre><code>for(int i=0;i<3;i++)\n  for(int j=0;j<4;j++)\n    {/* 内层 */}</code></pre>", options: ["3", "4", "7", "12"], answer: 3, explanation: "外层3次 × 内层4次 = 12次。" },
        { id: "kp05_q06", type: "choice", difficulty: 3, question: "下面C++代码输出是（ ）。\n<pre><code>int tnt = 0;\nfor (i = 0; i < 100; i++)\n    tnt += i % 10;\ncout << tnt;</code></pre>", options: ["4950", "5050", "450", "100"], answer: 2, explanation: "i%10 得个位0-9之和=45，共10组(0-99)，45×10=450。", source: "2024_12" },
        { id: "kp05_q07", type: "choice", difficulty: 2, question: "while(1) continue; 会导致死循环。（ ）", options: ["正确", "错误"], answer: 0, explanation: "while(1) 条件永远为 true，continue 重新判断条件后仍为 true。", source: "2023_12", isJudge: true },
        { id: "kp05_q08", type: "choice", difficulty: 2, question: "for循环中声明的变量在循环外访问会编译错误。（ ）", options: ["正确", "错误"], answer: 0, explanation: "C++ 中 for 循环内声明的变量作用域仅限循环内部。", source: "2024_09", isJudge: true },
        { id: "kp05_q09", type: "choice", difficulty: 3, question: "下面C++代码输出的是（ ）。\n<pre><code>int tnt = 0;\nfor (int i = 5; i < 100; i += 5) {\n    if (i % 2 == 0) continue;\n    tnt += 1;\n    if (i % 3 == 0 && i % 7 == 0) break;\n}\ncout << tnt;</code></pre>", options: ["500", "450", "10", "1"], answer: 2, explanation: "i取5的奇数倍:5,15,25,35,45,55,65,75,85,95。i%3==0&&i%7==0时break(即i=105时，不在范围内)。tnt=10。", source: "2025_03" },
        { id: "kp05_q10", type: "choice", difficulty: 2, question: "下面代码输出是（ ）。\n<pre><code>int Sum = 0, i = 0;\nfor ( ; i < 10; )\n    Sum += i++;\ncout << i << \" \" << Sum;</code></pre>", options: ["9 45", "10 55", "10 45", "11 55"], answer: 2, explanation: "i从0到9(共10次)，Sum=0+1+...+9=45，i++后i=10退出。", source: "2024_06" },
        { id: "kp05_q11", type: "choice", difficulty: 2, question: "for循环可以转化为等价的while循环。（ ）", options: ["正确", "错误"], answer: 0, explanation: "for(init;cond;update){body} 等价于 init; while(cond){body; update;}", source: "2024_03", isJudge: true },
        { id: "kp05_q12", type: "choice", difficulty: 2, question: "下面C++代码输出是（ ）。\n<pre><code>int N = 0, i;\nfor (i = 1; i < 10; i++)\n    N += 1;\ncout << (N + i);</code></pre>", options: ["54", "20", "19", "18"], answer: 1, explanation: "循环9次N=9，退出时i=10，但i先自增到10后退出。N+i=9+10=19。但实际答案是20? 让我确认: i从1开始，循环体执行9次(i=1到9)，N=9。退出循环时i=10。但等等 i++ 在for更新部分，i=9时进入循环后i++变为10，然后检查10<10为false退出。所以N=9,i=10,N+i=19。选项C=19。", source: "2024_12" },
        { id: "kp05_q13", type: "choice", difficulty: 2, question: "continue语句通常与if语句配合使用。（ ）", options: ["正确", "错误"], answer: 0, explanation: "continue 通常在 if 条件满足时使用，跳过当前循环的剩余部分。", source: "2024_06", isJudge: true },
        { id: "kp05_q14", type: "coding", difficulty: 1, question: "编写程序，计算 1+2+3+...+100 的和并输出。\n<p>预期输出：<code>5050</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    // 计算 1 到 100 的和\n    \n    return 0;\n}", testCases: [{ input: "", expectedOutput: "5050", description: "1+2+...+100=5050" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int sum = 0;\n    for (int i = 1; i <= 100; i++) sum += i;\n    cout << sum << endl;\n    return 0;\n}", explanation: "用 for 循环从1累加到100。" },
        { id: "kp05_q15", type: "coding", difficulty: 2, question: "编写程序，读入正整数n，计算n的阶乘n!（1×2×3×...×n）。\n<p>测试输入：<code>5</code></p>\n<p>预期输出：<code>120</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    long long result = 1;\n    for (int i = 1; i <= n; i++) result *= i;\n    cout << result << endl;\n    return 0;\n}", testCases: [{ input: "5", expectedOutput: "120", description: "5!=120" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    long long result = 1;\n    for (int i = 1; i <= n; i++) result *= i;\n    cout << result << endl;\n    return 0;\n}", explanation: "用 for 循环从1乘到n。" }
      ]
    },

    kp06: {
      title: "数组基础",
      subtitle: "掌握一维数组的声明、初始化、遍历与越界问题",
      theory: '<h4>1. 数组声明</h4>\n<pre>int a[5];\nint b[5] = {1,2,3,4,5};</pre>\n<h4>2. 索引从 0 开始</h4>\n<p>int a[5] 有效索引 a[0]~a[4]。</p>\n<h4>3. 部分初始化</h4>\n<p><code>int b[5]={1,2};</code> → b={1,2,0,0,0}</p>\n<h4>4. 遍历与 sizeof</h4>\n<pre>for(int i=0;i<5;i++) cout << a[i];\nsizeof(a)/sizeof(a[0]) // 元素个数</pre>\n<p class="warn">⚠ 数组越界是未定义行为！</p>',
      questions: [
        { id: "kp06_q01", type: "choice", difficulty: 1, question: "C++ 数组索引从哪个数字开始？", options: ["0", "1", "-1", "由大小决定"], answer: 0, explanation: "C++ 数组索引从 0 开始。" },
        { id: "kp06_q02", type: "choice", difficulty: 1, question: "以下哪种数组声明正确？", options: ["int a(5);", "int a[5];", "int a{5};", "array int a[5];"], answer: 1, explanation: "正确语法：类型 数组名[大小];" },
        { id: "kp06_q03", type: "choice", difficulty: 2, question: "int a[3]={1,2,3}; cout << a[3]; 会？", options: ["输出3", "输出0", "编译错误", "未定义行为"], answer: 3, explanation: "a[3] 超出范围(a[0]~a[2])，未定义行为。" },
        { id: "kp06_q04", type: "choice", difficulty: 2, question: "int b[5]={1,2}; 后 b[4] 是？", options: ["2", "0", "未定义", "编译错误"], answer: 1, explanation: "部分初始化，未赋值元素为 0。" },
        { id: "kp06_q05", type: "choice", difficulty: 2, question: "获取数组长度的正确方式？", options: ["a.length()", "sizeof(a)", "sizeof(a)/sizeof(a[0])", "a.size()"], answer: 2, explanation: "sizeof(a)/sizeof(a[0]) 得到元素个数。" },
        { id: "kp06_q06", type: "choice", difficulty: 3, question: "数组作为函数参数时？", options: ["完整复制", "传递首元素地址", "不能修改", "必须指定大小"], answer: 1, explanation: "传递的是首元素地址（指针）。" },
        { id: "kp06_q07", type: "choice", difficulty: 1, question: "int a[5]; 有效下标范围是？", options: ["1~5", "0~5", "0~4", "1~4"], answer: 2, explanation: "下标从0开始，0~4。", source: "mock_exam" },
        { id: "kp06_q08", type: "choice", difficulty: 2, question: "C++中表达式(!!N)的值也是N的值。（ ）", options: ["正确", "错误"], answer: 1, explanation: "!!N 只能是0或1，不等于N原值。N=5时!!N=1。", source: "2024_06", isJudge: true },
        { id: "kp06_q09", type: "choice", difficulty: 2, question: "C++中cin是合法的变量名。（ ）", options: ["正确", "错误"], answer: 0, explanation: "cin 不是关键字，可以作为变量名。", source: "2024_03", isJudge: true },
        { id: "kp06_q10", type: "choice", difficulty: 2, question: "下面代码输出cnt的值是（ ）。\n<pre><code>int cnt=0;\nfor(int i=0; i*i<64; i+=2) cnt++;\ncout << cnt;</code></pre>", options: ["8", "7", "4", "1"], answer: 2, explanation: "i=0,2,4,6(对应i*i=0,4,16,36都<64)，i=8时64<64为false。cnt=4。", source: "2024_06" },
        { id: "kp06_q11", type: "choice", difficulty: 2, question: "Dev C++中源文件生成可执行程序需要？", options: ["创建", "编辑", "编译", "调试"], answer: 2, explanation: "源代码需经过编译生成可执行程序。", source: "2024_03" },
        { id: "kp06_q12", type: "choice", difficulty: 2, question: "C++程序中不能用scanf作为变量名。（ ）", options: ["正确", "错误"], answer: 0, explanation: "scanf 是标准库函数名，作为变量名会出问题。", source: "2023_12", isJudge: true },
        { id: "kp06_q13", type: "choice", difficulty: 3, question: "判断完全平方数，横线处应填（ ）。\n<pre><code>for(int i=0;i<=N;i++)\n    if(________) cout<<N<<\"是完全平方数\";</code></pre>", options: ["i==N*N", "i*10==N", "i+i==N", "i*i==N"], answer: 3, explanation: "完全平方数满足 i*i==N。", source: "2024_06" },
        { id: "kp06_q14", type: "coding", difficulty: 2, question: "读入5个整数到数组，找出最大值。\n<p>输入：<code>3 7 2 9 5</code></p>\n<p>输出：<code>9</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for(int i=0;i<5;i++) cin >> a[i];\n    // 找最大值\n    \n    return 0;\n}", testCases: [{ input: "3 7 2 9 5", expectedOutput: "9", description: "最大值9" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for(int i=0;i<5;i++) cin >> a[i];\n    int mx=a[0];\n    for(int i=1;i<5;i++) if(a[i]>mx) mx=a[i];\n    cout << mx << endl;\n    return 0;\n}", explanation: "假设第一个最大，遍历比较更新。" },
        { id: "kp06_q15", type: "coding", difficulty: 2, question: "读入5个整数到数组，逆序输出（空格分隔）。\n<p>输入：<code>1 2 3 4 5</code></p>\n<p>输出：<code>5 4 3 2 1</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for(int i=0;i<5;i++) cin >> a[i];\n    // 逆序输出\n    \n    return 0;\n}", testCases: [{ input: "1 2 3 4 5", expectedOutput: "5 4 3 2 1", description: "逆序输出" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for(int i=0;i<5;i++) cin >> a[i];\n    for(int i=4;i>=0;i--){\n        if(i<4) cout << \" \";\n        cout << a[i];\n    }\n    cout << endl;\n    return 0;\n}", explanation: "从最后一个元素向前遍历。" }
      ]
    },

    kp07: {
      title: "字符与字符串",
      subtitle: "掌握 char 类型与 string 类的基本用法",
      theory: '<h4>1. char 类型</h4>\n<ul>\n  <li>单引号：<code>char c = \'A\';</code></li>\n  <li>1字节，存 ASCII 码</li>\n  <li>\'A\'=65, \'a\'=97, \'0\'=48</li>\n</ul>\n<h4>2. string 类</h4>\n<pre>#include &lt;string&gt;\nstring s = "Hello";</pre>\n<h4>3. 操作</h4>\n<ul>\n  <li>拼接：s1 + s2</li>\n  <li>长度：s.length() 或 s.size()</li>\n  <li>访问：s[i]</li>\n</ul>\n<h4>4. 输入</h4>\n<p>cin >> s 遇空格停，getline(cin,s) 读整行。</p>',
      questions: [
        { id: "kp07_q01", type: "choice", difficulty: 1, question: "关于 char 和 string，正确的是？", options: ["完全相同", "char 存单个字符，string 存一串", "char 占更多内存", "string 只能存字母"], answer: 1, explanation: "char 是基本类型存一个字符，string 是类存任意长度。" },
        { id: "kp07_q02", type: "choice", difficulty: 1, question: "正确的 char 赋值？", options: ["char c=\"A\";", "char c='A';", "char c=A;", "string c='A';"], answer: 1, explanation: "char 用单引号。" },
        { id: "kp07_q03", type: "choice", difficulty: 2, question: "string a=\"Hello\", b=\" World\"，s=a+b 是？", options: ["Hello", " World", "Hello World", "编译错误"], answer: 2, explanation: "+ 拼接两个字符串。" },
        { id: "kp07_q04", type: "choice", difficulty: 1, question: "获取字符串长度的方式？", options: ["length()和size()结果相同", "结果不同", "只有length()", "只有size()"], answer: 0, explanation: "两个方法功能完全相同。" },
        { id: "kp07_q05", type: "choice", difficulty: 2, question: "输入\"Hello World\"后 cin>>s 是？", options: ["Hello World", "Hello", "World", "H"], answer: 1, explanation: "cin>>s 遇空格停。" },
        { id: "kp07_q06", type: "choice", difficulty: 2, question: "'A'的 ASCII 码是？", options: ["97", "65", "48", "0"], answer: 1, explanation: "'A'=65。" },
        { id: "kp07_q07", type: "choice", difficulty: 2, question: "string s=\"hello\"; s.length() 是？", options: ["4", "5", "6", "不确定"], answer: 1, explanation: "\"hello\" 有5个字符。", source: "mock_exam" },
        { id: "kp07_q08", type: "choice", difficulty: 2, question: "printf(\"Hello,GESP!\")说法错误的是( )。", options: ["双引号内可改英文", "双引号内可改Hello代码！", "双引号都可改两个单引号", "双引号都可改三个双引号"], answer: 2, explanation: "单引号表示 char，不能替代双引号。", source: "2024_09" },
        { id: "kp07_q09", type: "choice", difficulty: 2, question: "Dev C++是操作系统。（ ）", options: ["正确", "错误"], answer: 1, explanation: "Dev C++ 是 IDE 不是操作系统。", source: "2023_12", isJudge: true },
        { id: "kp07_q10", type: "choice", difficulty: 2, question: "下面代码能执行输出45。（ ）\n<pre><code>for(int i=0;i<10;i++) Sum+=i;\ncout<<Sum;</code></pre>", options: ["正确", "错误"], answer: 1, explanation: "Sum 未声明。", source: "2024_09", isJudge: true },
        { id: "kp07_q11", type: "choice", difficulty: 1, question: "GESP同一级别能力与编程语言无关。（ ）", options: ["正确", "错误"], answer: 0, explanation: "GESP 考核编程能力，可用不同语言认证。", source: "2024_06", isJudge: true },
        { id: "kp07_q12", type: "choice", difficulty: 2, question: "studentName、student_name、sStudentName 都是合法变量名。（ ）", options: ["正确", "错误"], answer: 0, explanation: "都只含字母、数字、下划线且不以数字开头。", source: "2024_12", isJudge: true },
        { id: "kp07_q13", type: "choice", difficulty: 2, question: "five-star不能做变量名因含连字符。（ ）", options: ["正确", "错误"], answer: 0, explanation: "变量名不能含连字符(-)。", source: "2024_09", isJudge: true },
        { id: "kp07_q14", type: "coding", difficulty: 2, question: "读入一行字符串，统计元音字母(a,e,i,o,u，不区分大小写)个数。\n<p>输入：<code>Hello World</code></p>\n<p>输出：<code>3</code></p>", starterCode: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    getline(cin, s);\n    // 统计元音\n    \n    return 0;\n}", testCases: [{ input: "Hello World", expectedOutput: "3", description: "e,o,o共3个" }], referenceCode: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    getline(cin, s);\n    int cnt=0;\n    for(int i=0;i<s.length();i++){\n        char c=s[i];\n        if(c=='a'||c=='e'||c=='i'||c=='o'||c=='u'||\n           c=='A'||c=='E'||c=='I'||c=='O'||c=='U') cnt++;\n    }\n    cout<<cnt<<endl;\n    return 0;\n}", explanation: "遍历字符串判断是否为元音。" },
        { id: "kp07_q15", type: "coding", difficulty: 2, question: "读入字符串，逆序输出。\n<p>输入：<code>abcde</code></p>\n<p>输出：<code>edcba</code></p>", starterCode: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    // 逆序输出\n    \n    return 0;\n}", testCases: [{ input: "abcde", expectedOutput: "edcba", description: "逆序" }], referenceCode: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    for(int i=s.length()-1;i>=0;i--) cout<<s[i];\n    cout<<endl;\n    return 0;\n}", explanation: "从最后字符向前遍历。" }

      ]
    },

    kp08: {
      title: "函数基础",
      subtitle: "掌握函数的声明、定义、参数传递与返回值",
      theory: '<h4>1. 函数定义</h4>\n<pre>返回类型 函数名(参数列表) {\n    // 函数体\n    return 返回值;\n}</pre>\n<h4>2. 函数声明（原型）</h4>\n<pre>int max2(int a, int b); // 声明</pre>\n<h4>3. 值传递</h4>\n<p>函数参数是副本，修改不影响外部变量。</p>\n<h4>4. void 函数</h4>\n<p>无返回值用 void，可用空 return 提前退出。</p>',
      questions: [
        { id: "kp08_q01", type: "choice", difficulty: 1, question: "关于C++函数，正确的是？", options: ["可以没有返回类型", "必须声明返回类型（含void）", "函数名可和变量名相同", "不能有参数"], answer: 1, explanation: "每个函数都必须有返回类型。" },
        { id: "kp08_q02", type: "choice", difficulty: 1, question: "以下代码输出什么？\n<pre><code>int f() { cout<<1; return 0; cout<<2; }\nint main(){ f(); return 0; }</code></pre>", options: ["12", "1", "2", "无输出"], answer: 1, explanation: "return 立即结束函数，cout<<2 不执行。" },
        { id: "kp08_q03", type: "choice", difficulty: 2, question: "关于 void 函数，正确的是？", options: ["不能用return", "return后不能有值", "必须末尾写return;", "不能调用其他函数"], answer: 1, explanation: "void 函数可用空 return 提前退出，但不能 return 值。" },
        { id: "kp08_q04", type: "choice", difficulty: 2, question: "关于函数参数，正确的是？", options: ["参数是全局变量", "参数是局部变量，函数内有效", "参数可在外部访问", "参数值不能修改"], answer: 1, explanation: "参数是局部变量，只在函数内有效。" },
        { id: "kp08_q05", type: "choice", difficulty: 2, question: "void change(int x){x=100;} main(){int a=5;change(a);cout<<a;} 输出？", options: ["100", "5", "编译错误", "0"], answer: 1, explanation: "值传递，函数内修改副本不影响外部 a。" },
        { id: "kp08_q06", type: "choice", difficulty: 3, question: "关于函数原型，正确的是？", options: ["必须写在main内", "告诉编译器函数名、参数和返回类型", "可选的", "必须包含函数体"], answer: 1, explanation: "函数原型告诉编译器函数接口信息。" },
        { id: "kp08_q07", type: "choice", difficulty: 2, question: "3.0和3值相等但存储空间不同。（ ）", options: ["正确", "错误"], answer: 0, explanation: "3.0是double占8字节，3是int占4字节。", source: "2024_03", isJudge: true },
        { id: "kp08_q08", type: "choice", difficulty: 2, question: "studentName等变量名都合法。（ ）", options: ["正确", "错误"], answer: 0, explanation: "只含字母、数字、下划线且不以数字开头。", source: "2024_12", isJudge: true },
        { id: "kp08_q09", type: "choice", difficulty: 2, question: "Dev C++是操作系统。（ ）", options: ["正确", "错误"], answer: 1, explanation: "Dev C++是IDE不是OS。", source: "2023_12", isJudge: true },
        { id: "kp08_q10", type: "choice", difficulty: 2, question: "C++程序中不能用scanf作为变量名。（ ）", options: ["正确", "错误"], answer: 0, explanation: "scanf是标准库函数名。", source: "2023_12", isJudge: true },
        { id: "kp08_q11", type: "choice", difficulty: 3, question: "判断质数，横线处应填（ ）。\n<pre><code>int cnt=0;\nfor(int i=1;i<N+1;i++)\n    if(____) cnt++;\nif(cnt==2) cout<<N<<\"是质数\";</code></pre>", options: ["N % i", "N % i == 0", "N / i == 0", "N / i"], answer: 1, explanation: "N%i==0 统计能整除的个数，cnt==2 时是质数。", source: "2024_03" },
        { id: "kp08_q12", type: "choice", difficulty: 2, question: "华为手表上的鸿蒙是？", options: ["小程序", "计时器", "操作系统", "神话人物"], answer: 2, explanation: "鸿蒙(HarmonyOS)是操作系统。", source: "2024_03" },
        { id: "kp08_q13", type: "choice", difficulty: 2, question: "现代计算机基于（ ）体系结构。", options: ["图灵", "冯·诺依曼", "阿塔纳索夫", "埃克特-莫克利"], answer: 1, explanation: "现代计算机基于冯·诺依曼体系结构。", source: "2023_12" },
        { id: "kp08_q14", type: "coding", difficulty: 2, question: "编写函数 int max2(int a,int b) 返回较大值。main中读入两个整数调用并输出。\n<p>输入：<code>5 8</code></p>\n<p>输出：<code>8</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint max2(int a, int b);\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << max2(a, b) << endl;\n    return 0;\n}", testCases: [{ input: "5 8", expectedOutput: "8", description: "较大值为8" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint max2(int a, int b) {\n    if (a > b) return a;\n    else return b;\n}\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << max2(a, b) << endl;\n    return 0;\n}", explanation: "比较 a 和 b 返回较大值。" },
        { id: "kp08_q15", type: "coding", difficulty: 3, question: "编写 bool isPrime(int n) 判断质数。main读入n输出\"是质数\"或\"不是质数\"。\n<p>输入：<code>7</code></p>\n<p>输出：<code>是质数</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nbool isPrime(int n);\n\nint main() {\n    int n;\n    cin >> n;\n    if (isPrime(n)) cout << \"是质数\" << endl;\n    else cout << \"不是质数\" << endl;\n    return 0;\n}", testCases: [{ input: "7", expectedOutput: "是质数", description: "7是质数" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nbool isPrime(int n) {\n    if (n <= 1) return false;\n    for (int i = 2; i*i <= n; i++)\n        if (n % i == 0) return false;\n    return true;\n}\n\nint main() {\n    int n;\n    cin >> n;\n    if (isPrime(n)) cout << \"是质数\" << endl;\n    else cout << \"不是质数\" << endl;\n    return 0;\n}", explanation: "从2试除到sqrt(n)，能整除则不是质数。" }
      ]
    }
  },

  mockExam: [
    { id: "ex_q01", type: "choice", difficulty: 1, question: "sizeof(int) 的结果是？", options: ["1", "2", "4", "8"], answer: 2, explanation: "int 通常占 4 字节。" },
    { id: "ex_q02", type: "choice", difficulty: 1, question: "以下哪个是合法的变量名？", options: ["3abc", "my-name", "_count", "class"], answer: 2, explanation: "变量名不能以数字开头、不能含连字符、不能是关键字。_count 合法。" },
    { id: "ex_q03", type: "choice", difficulty: 1, question: "表达式 17 / 5 的结果是？", options: ["3.4", "3", "4", "3.0"], answer: 1, explanation: "整数除法截断小数，17/5=3。" },
    { id: "ex_q04", type: "choice", difficulty: 1, question: "10 % 3 的结果是？", options: ["3", "1", "0", "3.33"], answer: 1, explanation: "10÷3=3余1。" },
    { id: "ex_q05", type: "choice", difficulty: 2, question: "cout << 3 + 4 * 5 输出？", options: ["35", "23", "20", "7"], answer: 1, explanation: "先乘后加，4*5=20, 3+20=23。" },
    { id: "ex_q06", type: "choice", difficulty: 2, question: "endl 和 \"\\n\" 的区别？", options: ["完全相同", "endl刷新缓冲区，\\n不会", "\\n刷新缓冲区", "都不能换行"], answer: 1, explanation: "endl 会刷新缓冲区。" },
    { id: "ex_q07", type: "choice", difficulty: 2, question: "if (a = 5) 这行代码会？", options: ["判断a是否等于5", "将a赋值为5且条件为真", "编译错误", "将a赋值为5且条件为假"], answer: 1, explanation: "= 是赋值，表达式值为5(非零)即为true。" },
    { id: "ex_q08", type: "choice", difficulty: 2, question: "do-while 与 while 的主要区别？", options: ["do-while更快", "do-while至少执行一次", "do-while不需要条件", "while不能嵌套"], answer: 1, explanation: "do-while 先执行再判断，至少执行一次。" },
    { id: "ex_q09", type: "choice", difficulty: 2, question: "以下哪个导致无限循环？", options: ["for(int i=0;i<10;i++)", "while(true)", "for(int i=10;i>0;i--)", "while(0)"], answer: 1, explanation: "while(true) 条件永远为真。" },
    { id: "ex_q10", type: "choice", difficulty: 1, question: "int a[5]; 有效下标范围？", options: ["1~5", "0~5", "0~4", "1~4"], answer: 2, explanation: "从0开始，0~4。" },
    { id: "ex_q11", type: "choice", difficulty: 2, question: "哪个表示单个字符？", options: ["\"A\"", "A", "'A'", "\\t"], answer: 2, explanation: "单引号表示 char。" },
    { id: "ex_q12", type: "choice", difficulty: 2, question: "string s=\"hello\"; s.length() 是？", options: ["4", "5", "6", "不确定"], answer: 1, explanation: "\"hello\" 有5个字符。" },
    { id: "ex_q13", type: "choice", difficulty: 3, question: "正确的函数声明？", options: ["int max(a,b);", "int max(int a,b);", "int max(int a,int b);", "max(int a,int b);"], answer: 2, explanation: "每个参数都要单独声明类型。" },
    { id: "ex_q14", type: "choice", difficulty: 2, question: "表达式 16 / 4 % 2 的值？", options: ["8", "4", "2", "0"], answer: 3, explanation: "16/4=4, 4%2=0。" },
    { id: "ex_q15", type: "choice", difficulty: 2, question: "N=12, cout<<(N%3+N/5) 输出？", options: ["6", "2", "6.4", "2.4"], answer: 1, explanation: "12%3=0, 12/5=2, 0+2=2。" },
    { id: "ex_q16", type: "coding", difficulty: 2, question: "读入两个整数，输出它们的和。\n<p>输入：<code>3 5</code></p>\n<p>输出：<code>8</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a + b << endl;\n    return 0;\n}", testCases: [{ input: "3 5", expectedOutput: "8", description: "3+5=8" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a + b << endl;\n    return 0;\n}", explanation: "读入两个整数输出和。" },
    { id: "ex_q17", type: "coding", difficulty: 2, question: "读入整数，输出\"正数\"\"负数\"\"零\"。\n<p>输入：<code>-5</code></p>\n<p>输出：<code>负数</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    if (n > 0) cout << \"正数\" << endl;\n    else if (n < 0) cout << \"负数\" << endl;\n    else cout << \"零\" << endl;\n    return 0;\n}", testCases: [{ input: "-5", expectedOutput: "负数", description: "负数判断" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    if (n > 0) cout << \"正数\" << endl;\n    else if (n < 0) cout << \"负数\" << endl;\n    else cout << \"零\" << endl;\n    return 0;\n}", explanation: "if-else if-else 判断。" },
    { id: "ex_q18", type: "coding", difficulty: 2, question: "读入n，输出1+2+...+n。\n<p>输入：<code>10</code></p>\n<p>输出：<code>55</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) sum += i;\n    cout << sum << endl;\n    return 0;\n}", testCases: [{ input: "10", expectedOutput: "55", description: "1+2+...+10=55" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    int sum = 0;\n    for (int i = 1; i <= n; i++) sum += i;\n    cout << sum << endl;\n    return 0;\n}", explanation: "for 循环累加。" },
    { id: "ex_q19", type: "coding", difficulty: 3, question: "读入5个整数，找出最大值。\n<p>输入：<code>3 7 2 9 5</code></p>\n<p>输出：<code>9</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for (int i = 0; i < 5; i++) cin >> a[i];\n    int mx = a[0];\n    for (int i = 1; i < 5; i++)\n        if (a[i] > mx) mx = a[i];\n    cout << mx << endl;\n    return 0;\n}", testCases: [{ input: "3 7 2 9 5", expectedOutput: "9", description: "最大值9" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a[5];\n    for (int i = 0; i < 5; i++) cin >> a[i];\n    int mx = a[0];\n    for (int i = 1; i < 5; i++)\n        if (a[i] > mx) mx = a[i];\n    cout << mx << endl;\n    return 0;\n}", explanation: "遍历数组找最大值。" },
    { id: "ex_q20", type: "coding", difficulty: 3, question: "编写函数计算n的阶乘。main读入n输出n!。\n<p>输入：<code>5</code></p>\n<p>输出：<code>120</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint factorial(int n) {\n    int result = 1;\n    for (int i = 1; i <= n; i++) result *= i;\n    return result;\n}\n\nint main() {\n    int n;\n    cin >> n;\n    cout << factorial(n) << endl;\n    return 0;\n}", testCases: [{ input: "5", expectedOutput: "120", description: "5!=120" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint factorial(int n) {\n    int result = 1;\n    for (int i = 1; i <= n; i++) result *= i;\n    return result;\n}\n\nint main() {\n    int n;\n    cin >> n;\n    cout << factorial(n) << endl;\n    return 0;\n}", explanation: "循环从1乘到n。" },
    { id: "ex_q21", type: "choice", difficulty: 1, question: "以下哪个不是C++关键字？", options: ["int", "double", "cin", "bool"], answer: 2, explanation: "cin 是标准输入对象，不是关键字。" },
    { id: "ex_q22", type: "choice", difficulty: 2, question: "表达式 5 > 3 的结果类型是？", options: ["int", "bool", "double", "string"], answer: 1, explanation: "比较运算结果是 bool 类型。" },
    { id: "ex_q23", type: "choice", difficulty: 2, question: "以下代码 count 最终是？\n<pre><code>int count=0;\nfor(int i=0;i<10;i+=2) count++;\n</code></pre>", options: ["5", "10", "4", "6"], answer: 0, explanation: "i=0,2,4,6,8 共5次。" },
    { id: "ex_q24", type: "choice", difficulty: 2, question: "char c = 'A' + 1; c 的值是？", options: ["'A'", "'B'", "66", "A1"], answer: 1, explanation: "'A'=65, 65+1=66='B'。" },
    { id: "ex_q25", type: "choice", difficulty: 2, question: "break 语句用于？", options: ["跳过本次循环", "跳出当前循环", "结束程序", "继续下一次"], answer: 1, explanation: "break 跳出当前循环。" },
    { id: "ex_q26", type: "choice", difficulty: 3, question: "以下哪个输出 \"5%2={1}\"？", options: ["printf(\"5%%2={%d}\", 5%2)", "printf(\"5%2={%d}\", 5%2)", "cout<<\"5%2={\"<<5%2<<\"}\"", "printf(\"5%2={1}\")"], answer: 0, explanation: "printf 中 %% 输出一个 %，%d 格式化整数。" },
    { id: "ex_q27", type: "choice", difficulty: 1, question: "以下哪个可以声明数组？", options: ["int a(5);", "int a[5];", "int a{5};", "array a[5];"], answer: 1, explanation: "正确语法：int a[5];" },
    { id: "ex_q28", type: "choice", difficulty: 2, question: "函数 return 语句会？", options: ["结束整个程序", "跳回调用处", "重启main", "输出结果"], answer: 1, explanation: "return 将控制权返回给调用者。" },
    { id: "ex_q29", type: "choice", difficulty: 2, question: "表达式 (3 - 2) * 3 + 5 的值？", options: ["-13", "8", "2", "0"], answer: 1, explanation: "(3-2)=1, 1*3=3, 3+5=8。", source: "2024_03" },
    { id: "ex_q30", type: "choice", difficulty: 2, question: "cout << \"5%2=\" << 5 % 2 执行后输出？", options: ["2 2", "1 1", "5%2=2", "5%2=1"], answer: 3, explanation: "5%2=1，输出 \"5%2=1\"。", source: "2024_03" }
  ],

  realExam: [
    { id: "real_2023_01", type: "choice", difficulty: 2, question: "以下C++不可以作为变量的名称的是( )。", options: ["CCF GESP", "ccfGESP", "CCFgesp", "CCF_GESP"], answer: 0, explanation: "变量名不能含空格。", source: "2023_12", examDate: "2023年12月" },
    { id: "real_2023_02", type: "choice", difficulty: 2, question: "C++表达式10 - 3 * (2 + 1) % 10的值是( )。", options: ["0", "1", "2", "3"], answer: 1, explanation: "10-3*(2+1)%10 = 10-3*3%10 = 10-9%10 = 10-9 = 1。", source: "2023_12", examDate: "2023年12月" },
    { id: "real_2024_03_01", type: "choice", difficulty: 2, question: "C++表达式(3 - 2) * 3 + 5的值是( )。", options: ["-13", "8", "2", "0"], answer: 1, explanation: "1*3+5=8。", source: "2024_03", examDate: "2024年3月" },
    { id: "real_2024_03_02", type: "choice", difficulty: 2, question: "cout << \"5%2=\" << 5 % 2 输出？", options: ["5%2=2", "5%2=1", "2 2", "1 1"], answer: 1, explanation: "5%2=1。", source: "2024_03", examDate: "2024年3月" },
    { id: "real_2024_06_01", type: "choice", difficulty: 2, question: "表达式3 - 3 * 3 / 5的值是( )。", options: ["-1.2", "1", "0", "2"], answer: 3, explanation: "3*3=9, 9/5=1, 3-1=2。", source: "2024_06", examDate: "2024年6月" },
    { id: "real_2024_06_02", type: "choice", difficulty: 2, question: "printf(\"5%%2={%d}\\n\",5%2) 输出？", options: ["5%2={1}", "5%2={5%2}", "1={1}", "5 ={1}"], answer: 0, explanation: "%%输出%,%d格式化1。", source: "2024_06", examDate: "2024年6月" },
    { id: "real_2024_09_01", type: "choice", difficulty: 2, question: "DJL-1计算机的磁心存储元件相当于现代计算机的（ ）。", options: ["内存", "磁盘", "CPU", "显示器"], answer: 0, explanation: "存储元件相当于内存。", source: "2024_09", examDate: "2024年9月" },
    { id: "real_2024_09_02", type: "choice", difficulty: 3, question: "for(int i=0,s=0;i<20;i++,count++) s+=i++; 输出s和count？", options: ["190 20", "95 10", "90 19", "90 10"], answer: 3, explanation: "i和count同时增加，s累加0,2,4,...,18共10项=90，count=10。", source: "2024_09", examDate: "2024年9月" },
    { id: "real_2024_12_01", type: "choice", difficulty: 2, question: "表达式12 - 3 * 2 && 2的值是( )。", options: ["0", "1", "6", "9"], answer: 1, explanation: "12-6=6, 6&&2=1(true)。", source: "2024_12", examDate: "2024年12月" },
    { id: "real_2024_12_02", type: "choice", difficulty: 2, question: "N=2, cout<<(N/3+N%3) 输出？", options: ["0", "2", "3", "4"], answer: 1, explanation: "2/3=0, 2%3=2, 0+2=2。", source: "2024_12", examDate: "2024年12月" },
    { id: "real_2025_01", type: "choice", difficulty: 2, question: "下面哪个不是驾驶系统完成选路所必须的？", options: ["麦克风", "扬声器", "油量表", "传感器"], answer: 2, explanation: "选路不需要油量表。", source: "2023_12", examDate: "2023年12月" },
    { id: "real_2025_02", type: "choice", difficulty: 2, question: "在C++中，下列可以做变量的是( )。", options: ["Var-1", "$1", "%%1", "_Var_1"], answer: 3, explanation: "_Var_1 合法。", source: "2025_03", examDate: "2025年3月" },
    { id: "real_2025_03", type: "choice", difficulty: 2, question: "C++表达式16 / 4 % 2的值是( )。", options: ["8", "4", "2", "0"], answer: 3, explanation: "16/4=4, 4%2=0。", source: "2025_03", examDate: "2025年3月" },
    { id: "real_prog_01", type: "coding", difficulty: 2, question: "今天是星期x，还有n天考试，求考试那天是星期几。（星期日用0表示）\n<p>输入第1行：星期几x</p>\n<p>输入第2行：天数n</p>\n<p>样例输入：<code>1\\n6</code></p>\n<p>样例输出：<code>0</code></p>", starterCode: "#include <stdio.h>\n\nint main() {\n    int x, n;\n    scanf(\"%d%d\", &x, &n);\n    // 计算星期几\n    \n    return 0;\n}", testCases: [{ input: "1\n6", expectedOutput: "0", description: "星期1+6天=星期日(0)" }, { input: "5\n3", expectedOutput: "1", description: "星期5+3天=星期1" }], referenceCode: "#include <stdio.h>\n\nint main() {\n    int x, n;\n    scanf(\"%d%d\", &x, &n);\n    printf(\"%d\\n\", (x-1+n%7)%7+1);\n    return 0;\n}", explanation: "用取余运算处理星期推算。", source: "2023_12", examDate: "2023年12月" },
    { id: "real_prog_02", type: "coding", difficulty: 2, question: "从1到n报数，跳过m的倍数。依次输出报的数。\n<p>样例输入：<code>5\\n2</code></p>\n<p>样例输出：<code>1\\n3\\n5</code></p>", starterCode: "#include <stdio.h>\n\nint main() {\n    int n, m;\n    scanf(\"%d%d\", &n, &m);\n    // 输出非m倍数的数\n    \n    return 0;\n}", testCases: [{ input: "5\n2", expectedOutput: "1\n3\n5", description: "跳过2的倍数" }], referenceCode: "#include <stdio.h>\n\nint main() {\n    int n, m;\n    scanf(\"%d%d\", &n, &m);\n    for(int i=1; i<=n; i++)\n        if(i%m!=0) printf(\"%d\\n\", i);\n    return 0;\n}", explanation: "遍历1到n，输出不是m倍数的数。", source: "2023_12", examDate: "2023年12月" },
    { id: "real_prog_03", type: "coding", difficulty: 2, question: "一本书13元，输入零用钱数，输出最多买几本和剩余钱数。\n<p>样例输入：<code>100</code></p>\n<p>样例输出：<code>7\\n9</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int m;\n    cin >> m;\n    // 计算本数和余数\n    \n    return 0;\n}", testCases: [{ input: "100", expectedOutput: "7\n9", description: "100/13=7余9" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int m;\n    cin >> m;\n    cout << m / 13 << endl;\n    cout << m % 13 << endl;\n    return 0;\n}", explanation: "整除得本数，取余得剩余。", source: "2024_03", examDate: "2024年3月" },
    { id: "real_prog_04", type: "coding", difficulty: 2, question: "从小到大输出正整数n的所有因数。\n<p>样例输入：<code>6</code></p>\n<p>样例输出：<code>1\\n2\\n3\\n6</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a;\n    cin >> a;\n    // 输出所有因数\n    \n    return 0;\n}", testCases: [{ input: "6", expectedOutput: "1\n2\n3\n6", description: "6的因数" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a;\n    cin >> a;\n    for (int i = 1; i <= a; i++)\n        if (a % i == 0) cout << i << endl;\n    return 0;\n}", explanation: "遍历1到n，能整除的即是因数。", source: "2024_03", examDate: "2024年3月" },
    { id: "real_prog_05", type: "coding", difficulty: 2, question: "图书馆n本书，老鼠每x小时啃一本书，y小时后剩几本。\n<p>样例输入：<code>10\\n2\\n3</code></p>\n<p>样例输出：<code>8</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n, x, y;\n    cin >> n >> x >> y;\n    // 计算剩余\n    \n    return 0;\n}", testCases: [{ input: "10\n2\n3", expectedOutput: "8", description: "10-3/2-1+(3%2==0)=8" }], referenceCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n, x, y;\n    cin >> n >> x >> y;\n    cout << n - y / x - 1 + (y % x == 0) << '\\n';\n    return 0;\n}", explanation: "计算啃掉的书数，注意边界条件。", source: "2025_03", examDate: "2025年3月" },

    // ===== 2023年12月 真题补充 =====
    { id: "r2312_q03", type: "choice", difficulty: 2, question: "假设现在是上午十点，求出N小时（正整数）后是第几天几时，如输入20小时则为第2天6点，如N输入4则为今天14点。为实现相应功能，应在横线处填写代码是( )。\n<pre><code>int day, hour;\nday = ________;\nhour = ________;</code></pre>", options: ["(10+N)%24, (10+N)/24", "(10+N)/24, (10+N)%24", "N%24, N/24", "10/24, 10%24"], answer: 1, explanation: "(10+N)/24得天数，(10+N)%24得小时数。如10+20=30, 30/24=1天, 30%24=6时。", source: "2023_12", examDate: "2023年12月" },
    { id: "r2312_q04", type: "choice", difficulty: 1, question: "下面的程序用于判断N是否为偶数，横线处应填写代码是（ ）。\n<pre><code>if (_______) cout << N << \"是偶数\";</code></pre>", options: ["N%2==0", "N%2=0", "N%2", "N%2!=0"], answer: 0, explanation: "N%2==0判断N是否为偶数。N%2=0是赋值不是比较，N%2非零为true表示奇数。", source: "2023_12", examDate: "2023年12月" },

    // ===== 2024年03月 真题补充 =====
    { id: "r2403_q03", type: "choice", difficulty: 2, question: "执行C++语句cin >> a时如果输入5+2，下述说法正确的是（ ）。", options: ["变量a将被赋值为整数7", "变量a将被赋值为字符串\"5+2\"", "语句执行将报错", "取决于变量a的类型"], answer: 3, explanation: "如果a是int，cin只读入5；如果a未定义则编译错误。行为取决于a的类型。", source: "2024_03", examDate: "2024年3月" },
    { id: "r2403_q07", type: "choice", difficulty: 2, question: "下面C++代码第2行，总共被执行次数是（ ）。\n<pre><code>for(int i=-10; i<10; i++)\n    cout << i << \" \";</code></pre>", options: ["10", "19", "20", "21"], answer: 2, explanation: "i从-10到9，共20次循环。", source: "2024_03", examDate: "2024年3月" },
    { id: "r2403_q08", type: "choice", difficulty: 3, question: "下面C++代码执行后的输出是（ ）。\n<pre><code>int tnt = 0;\nfor(int i=0; i<10; i++)\n    if(i%3 && i%7)\n        tnt += i;\ncout << tnt << endl;</code></pre>", options: ["0", "7", "18", "20"], answer: 3, explanation: "i%3&&i%7筛选出既不被3整除也不被7整除的数：1+2+4+5+8=20。", source: "2024_03", examDate: "2024年3月" },
    { id: "r2403_q09", type: "choice", difficulty: 2, question: "下面C++代码执行后的输出是（ ）。\n<pre><code>int N = 10;\nwhile(N){\n    N -= 1;\n    if(N%3 == 0)\n        cout << N << \"#\";\n}</code></pre>", options: ["9#6#3#", "9#6#3#0#", "8#7#5#4#2#1#", "10#8#7#5#4#2#1#"], answer: 0, explanation: "N递减：9→9%3=0输出, 6→6%3=0输出, 3→3%3=0输出, 0→while(0)退出。", source: "2024_03", examDate: "2024年3月" },
    { id: "r2403_tf02", type: "choice", difficulty: 1, question: "C++语句printf(\"%d#%d&\",2,3)执行后输出的是2#3&。（ ）", options: ["正确", "错误"], answer: 0, explanation: "%d格式化整数2和3，#和&是普通字符原样输出。", source: "2024_03", examDate: "2024年3月", isJudge: true },
    { id: "r2403_tf04", type: "choice", difficulty: 2, question: "C++表达式\"10\"*2执行时将报错，因为\"10\"是字符串类型而2是整数类型，它们数据类型不同，不能在一起运算。（ ）", options: ["正确", "错误"], answer: 0, explanation: "字符串不能与整数相乘，会编译报错。", source: "2024_03", examDate: "2024年3月", isJudge: true },
    { id: "r2403_tf09", type: "choice", difficulty: 1, question: "小杨奶奶家的数字电视可以通过遥控器输入电视剧名称来找到想播放的电视剧，所以可以推知里面有交互式程序在运行。（ ）", options: ["正确", "错误"], answer: 0, explanation: "数字电视接收用户输入并响应，说明有交互式程序。", source: "2024_03", examDate: "2024年3月", isJudge: true },

    // ===== 2024年06月 真题补充 =====
    { id: "r2406_q08", type: "choice", difficulty: 2, question: "下面C++代码执行时输入10后，正确的输出是（ ）。\n<pre><code>int N;\ncout << \"请输入正整数：\";\ncin >> N;\nif (N % 3)\n    printf(\"第5行代码%2d\", N % 3);\nelse\n    printf(\"第6行代码%2d\", N % 3);</code></pre>", options: ["第5行代码1", "第6行代码1", "第5行代码 1", "第6行代码 1"], answer: 2, explanation: "N=10, 10%3=1(非零为true)，执行if分支。%2d占2位右对齐，输出\"第5行代码 1\"。", source: "2024_06", examDate: "2024年6月" },
    { id: "r2406_q11", type: "choice", difficulty: 3, question: "下面的C++代码用于求1~N之间所有奇数之和，其中N为正整数。有关描述错误的是（ ）。\n<pre><code>int N;\ncin >> N;\nint i = 1, Sum = 0;\nwhile (i <= N){\n    if (i % 2 == 1)\n        Sum += i;\n    i += 1;\n}\ncout << i << \" \" << Sum;</code></pre>", options: ["输入10，输出11 25", "输入5，输出6 9", "将i+=1移到if前一行，同样能实现要求", "删除if并改i+=1为i+=2，同样能实现要求"], answer: 2, explanation: "将i+=1移到if前，i先加1再判断奇偶，导致所有偶数被跳过，求和结果错误。", source: "2024_06", examDate: "2024年6月" },
    { id: "r2406_tf01", type: "choice", difficulty: 2, question: "在C++代码中变量X被赋值为16.44，则cout << X / 10执行后输出的一定是1。（ ）", options: ["正确", "错误"], answer: 1, explanation: "如果X是double类型，16.44/10=1.644，不一定是1。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "r2406_tf02", type: "choice", difficulty: 2, question: "C++的整型变量N被赋值为10，则语句cout << N / 4 << \"->\" << N % 4 << \"->\" << N / 4.0执行后输出是2->2->2.0。（ ）", options: ["正确", "错误"], answer: 1, explanation: "N/4.0=2.5(不是2.0)，输出为\"2->2->2.5\"。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "r2406_tf03", type: "choice", difficulty: 2, question: "定义C++的float型变量N，则语句cin >> N; cout << int(float(N))可以输入正负整数和浮点数，并将其转换为整数后输出。（ ）", options: ["正确", "错误"], answer: 0, explanation: "float可接受整数和浮点数输入，int()强制转换截断小数部分。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "r2406_tf04", type: "choice", difficulty: 1, question: "C++的整型N被赋值为5，语句printf(\"%d*2\",N)执行后将输出10。（ ）", options: ["正确", "错误"], answer: 1, explanation: "printf(\"%d*2\",5)输出\"5*2\"，*2是普通字符不是乘法。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "r2406_tf07", type: "choice", difficulty: 2, question: "在C++代码中，不可以将变量命名为printf，因为printf是C++语言的关键字。（ ）", options: ["正确", "错误"], answer: 1, explanation: "printf是标准库函数名，不是关键字。可以作变量名（但不推荐）。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "r2406_tf08", type: "choice", difficulty: 3, question: "在C++中有整型变量N，则表达式N += 8/4//2相当于N += 8/(4/2)。（ ）", options: ["正确", "错误"], answer: 1, explanation: "//在C++中是注释符，8/4//2实际等于8/4=2。", source: "2024_06", examDate: "2024年6月", isJudge: true },
    { id: "real_prog_2406_01", type: "coding", difficulty: 2, question: "休息时间：小杨计划在某个时刻开始学习，并决定在学习k秒后开始休息。求开始休息的时刻。\n<p>输入：前三行分别是时h、分m、秒s，第四行是学习总秒数k</p>\n<p>输出：一行三个整数，休息时刻的时、分、秒</p>\n<p>样例输入：<code>12\\n59\\n59\\n10</code></p>\n<p>样例输出：<code>13 0 9</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int h, m, s, k;\n    cin >> h >> m >> s >> k;\n    // 计算休息时刻\n    \n    return 0;\n}", testCases: [{ input: "12\n59\n59\n10", expectedOutput: "13 0 9", description: "12:59:59 + 10秒 = 13:00:09" }], referenceCode: "#include <iostream>\nusing namespace std;\nint main() {\n    int h, m, s, k;\n    cin >> h >> m >> s >> k;\n    int now = h*3600 + m*60 + s;\n    now += k;\n    int hh = now / 3600;\n    now %= 3600;\n    int mm = now / 60;\n    now %= 60;\n    cout << hh << \" \" << mm << \" \" << now << endl;\n    return 0;\n}", explanation: "先将时分秒转为总秒数，加上k秒后再转回时分秒。", source: "2024_06", examDate: "2024年6月" },
    { id: "real_prog_2406_02", type: "coding", difficulty: 2, question: "立方数：小杨有一个正整数N，他想知道N是否是一个立方数。一个正整数N是立方数当且仅当存在正整数X满足X*X*X = N。\n<p>输入：一个正整数N</p>\n<p>输出：如果是立方数输出\"Yes\"，否则输出\"No\"</p>\n<p>样例输入1：<code>8</code> 样例输出1：<code>Yes</code></p>\n<p>样例输入2：<code>9</code> 样例输出2：<code>No</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // 判断是否为立方数\n    \n    return 0;\n}", testCases: [{ input: "8", expectedOutput: "Yes", description: "2^3=8" }, { input: "9", expectedOutput: "No", description: "9不是立方数" }], referenceCode: "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int fl = 0;\n    for (int i = 1; i <= n; i++) {\n        if (i*i*i == n) { fl = 1; break; }\n    }\n    if (fl) cout << \"Yes\" << endl;\n    else cout << \"No\" << endl;\n    return 0;\n}", explanation: "遍历i从1到n，检查i*i*i是否等于n。", source: "2024_06", examDate: "2024年6月" },

    // ===== 2024年09月 真题补充 =====
    { id: "r2409_q02", type: "choice", difficulty: 1, question: "C++程序执行出现错误，不太常见的调试手段是（ ）。", options: ["阅读源代码", "单步调试", "输出执行中间结果", "跟踪汇编码"], answer: 3, explanation: "跟踪汇编码对初学者来说不常见。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q05", type: "choice", difficulty: 2, question: "在C++中，假设N为正整数10，则cout << (N / 3 + N % 3)将输出（ ）。", options: ["6", "4.3", "4", "2"], answer: 2, explanation: "N/3=10/3=3, N%3=10%3=1, 3+1=4。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q07", type: "choice", difficulty: 2, question: "成功执行下面的C++代码，先后从键盘上输入5回车和2回车，输出是（ ）。\n<pre><code>cin >> a;\ncin >> b;\ncout << a + b;</code></pre>", options: ["将输出整数7", "将输出52", "将输出5和2，之间有空格", "执行结果不确定，因为没有显示a和b的数据类型"], answer: 3, explanation: "不知道a和b的类型，无法确定输出。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q08", type: "choice", difficulty: 2, question: "下面C++代码执行后输出是（ ）。\n<pre><code>int Sum = 0;\nfor (int i = 0; i < 10; i++)\n    Sum += i;\ncout << Sum;</code></pre>", options: ["55", "45", "10", "9"], answer: 1, explanation: "Sum = 0+1+2+...+9 = 45。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q09", type: "choice", difficulty: 2, question: "下面C++代码执行后输出的是（ ）。\n<pre><code>int N = 0;\nfor (int i = 0; i < 10; i++)\n    N += 1;\ncout << N;</code></pre>", options: ["55", "45", "10", "9"], answer: 2, explanation: "循环10次，N每次加1，N=10。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q10", type: "choice", difficulty: 3, question: "下面C++代码执行后输出的是（ ）。\n<pre><code>int N = 0;\nfor (int i = 1; i < 10; i += 2){\n    if (i % 2 == 1)\n        continue;\n    N += 1;\n}\ncout << N;</code></pre>", options: ["5", "4", "2", "0"], answer: 3, explanation: "i从1开始每次加2，永远是奇数，i%2==1恒为true，continue每次都执行，N永远不加。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_q15", type: "choice", difficulty: 3, question: "如果正整数N能表示为X*(X+1)的形式，称它是\"兄弟数\"。下面代码判断N是否为兄弟数，横线处应填入的代码有几个能完成功能？（ ）\n<pre><code>int N;\ncin >> N;\nfor(int i = 0; i <= N; i++)\n    if(___________________)\n        cout << N << \"是一个兄弟数\";</code></pre>\ni) N==i*(i+1)  ii) N==i*(i-1)  iii) N/(i+1)==i  iv) N/(i-1)==i", options: ["1个", "2个", "3个", "4个"], answer: 2, explanation: "i)直接乘法可以；ii)等价于(i-1)*i也可以；iii)整数除法可以；iv)i=0时除零错误。共3个。", source: "2024_09", examDate: "2024年9月" },
    { id: "r2409_tf01", type: "choice", difficulty: 1, question: "小杨最近开始学习C++编程，老师说C++是一门面向对象的编程语言，也是一门高级语言。（ ）", options: ["正确", "错误"], answer: 0, explanation: "C++确实是面向对象的高级编程语言。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf02", type: "choice", difficulty: 2, question: "在C++中，表达式10/4和10%4的值相同，都是整数2，说明/和%可以互相替换。（ ）", options: ["正确", "错误"], answer: 1, explanation: "虽然10/4=2和10%4=2碰巧相同，但/和%含义不同，如10/3=3而10%3=1。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf03", type: "choice", difficulty: 2, question: "N是C++程序中的整型变量，则语句scanf(\"%d\", &N)能接收正整数、负整数和0输入，但如果输入含字母或带小数点数，将导致无法执行。（ ）", options: ["正确", "错误"], answer: 1, explanation: "scanf遇到无效输入不会导致程序崩溃，只是无法读取，程序继续执行。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf05", type: "choice", difficulty: 3, question: "在C++代码中整型变量X被赋值为20.24，则cout << (X++, X+1) / 10执行后输出的是2.124。（ ）", options: ["正确", "错误"], answer: 1, explanation: "X是int，X=20。X++后X=21。(X++,X+1)逗号运算符返回22。22/10=2(整数除法)。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf07", type: "choice", difficulty: 1, question: "在C++，break语句通常与if语句配合使用。（ ）", options: ["正确", "错误"], answer: 0, explanation: "break通常放在if条件内，满足条件时跳出循环。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf08", type: "choice", difficulty: 1, question: "在C++代码中，不可以将变量命名为five-star，因为变量名中不可以出现-（减号）符号。（ ）", options: ["正确", "错误"], answer: 0, explanation: "变量名只能包含字母、数字和下划线，不能包含连字符。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf09", type: "choice", difficulty: 2, question: "在C++语言中，整型、实数型、字符型、布尔型是不同数据类型，但这四种类型的变量间都可以比较大小。（ ）", options: ["正确", "错误"], answer: 0, explanation: "C++允许不同类型间隐式转换后进行比较。", source: "2024_09", examDate: "2024年9月", isJudge: true },
    { id: "r2409_tf10", type: "choice", difficulty: 3, question: "C++中，定义变量int a=5,b=4,c=3，则表达式(a<b<c)的值为逻辑假。（ ）", options: ["正确", "错误"], answer: 1, explanation: "C++从左到右计算：(5<4)=0，然后(0<3)=1(真)。表达式值为1(真)，不是假。", source: "2024_09", examDate: "2024年9月", isJudge: true },

    // ===== 2024年12月 真题补充 =====
    { id: "r2412_q01", type: "choice", difficulty: 1, question: "2024年诺贝尔物理学奖颁给了约翰·霍普菲尔德和杰弗里·辛顿，这两位科学家的主要研究方向是（ ）。", options: ["天体物理", "流体力学", "人工智能", "量子理论"], answer: 2, explanation: "两位因机器学习和人工神经网络的突破性贡献获奖。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q02", type: "choice", difficulty: 1, question: "下列软件中是操作系统的是（ ）。", options: ["高德地图", "腾讯会议", "纯血鸿蒙", "金山永中"], answer: 2, explanation: "纯血鸿蒙(HarmonyOS NEXT)是操作系统。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q03", type: "choice", difficulty: 2, question: "有关下列C++代码的说法，正确的是( )。\n<pre><code>printf(\"Hello,GESP!\");</code></pre>", options: ["配对双引号内不可以有汉字", "双引号可改为单引号而输出效果不变", "双引号可改为三个连续单引号而输出效果不变", "双引号可改为三个连续双引号而输出效果不变"], answer: 3, explanation: "双引号用于字符串，不能改为单引号（单引号是char）。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q07", type: "choice", difficulty: 2, question: "下面代码求几天后星期几，如果N%7==0则输出\"星期天\"，否则输出\"星期N%7\"。横线处应填（ ）。\n<pre><code>if(_________________)\n    printf(\"星期天\");\nelse\n    printf(\"星期%d\", N%7);</code></pre>", options: ["N%7!=0", "N%7==0", "N==0", "N%7"], answer: 1, explanation: "N%7==0时为星期天。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q08", type: "choice", difficulty: 2, question: "下面C++代码执行后输出是（ ）。\n<pre><code>int N=0, i;\nfor (i = 1; i < 10; i++)\n    N += 1;\ncout << (N + i);</code></pre>", options: ["54", "20", "19", "18"], answer: 2, explanation: "循环i=1到9共9次，N=9。退出时i=10。N+i=9+10=19。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q09", type: "choice", difficulty: 2, question: "下面C++代码执行后输出的是（ ）。\n<pre><code>int tnt = 0;\nfor (i = 0; i < 100; i++)\n    tnt += i % 10;\ncout << tnt;</code></pre>", options: ["4950", "5050", "450", "100"], answer: 2, explanation: "i%10循环0~9，和为45。100次=10个完整周期，tnt=45×10=450。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q10", type: "choice", difficulty: 3, question: "下面C++代码执行后输出的是（ ）。\n<pre><code>int tnt = 0;\nfor (i = 5; i < 100; i += 5){\n    if (i % 2 == 0) continue;\n    tnt += 1;\n    if (i >= 50) break;\n}\ncout << tnt;</code></pre>", options: ["10", "9", "6", "5"], answer: 2, explanation: "i=5(odd,tnt=1),10(even,skip),15(tnt=2),20(skip),25(tnt=3),30(skip),35(tnt=4),40(skip),45(tnt=5),50(skip?50%2=0 skip),55(tnt=6,i>=50 break)。等等，50%2=0跳过，55是奇数tnt=6然后break。答案6。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q12", type: "choice", difficulty: 3, question: "下面C++代码执行后的输出是（ ）。\n<pre><code>int cnt = 0;\nfor(int i = 1; i < 10; i++)\n    cnt += i++;\ncout << cnt;</code></pre>", options: ["54", "45", "25", "10"], answer: 2, explanation: "i=1:cnt=1,i→2; i=3:cnt=4,i→4; i=5:cnt=9,i→6; i=7:cnt=16,i→8; i=9:cnt=25,i→10退出。cnt=25。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_q13", type: "choice", difficulty: 2, question: "int变量a=4（正方形边长），下列哪个语句执行后能使正方形周长增加4？（ ）", options: ["a*4;", "a+4;", "a+1;", "++a;"], answer: 3, explanation: "只有++a会修改a的值（a变为5），周长从16变为20，增加4。其他语句不修改a。", source: "2024_12", examDate: "2024年12月" },
    { id: "r2412_tf01", type: "choice", difficulty: 1, question: "在Windows资源管理器中为已有文件A建立副本的操作是Ctrl+C，然后Ctrl+V。（ ）", options: ["正确", "错误"], answer: 0, explanation: "Ctrl+C复制，Ctrl+V粘贴，可以建立文件副本。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf02", type: "choice", difficulty: 2, question: "在C++中，表达式8/3和8%3的值相同。（ ）", options: ["正确", "错误"], answer: 0, explanation: "8/3=2，8%3=2，此例中确实相同。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf03", type: "choice", difficulty: 1, question: "X是C++语言的基本类型变量，则语句cin>>X, cout<<X能接收键盘输入并原样输出。（ ）", options: ["正确", "错误"], answer: 0, explanation: "cin读入基本类型，cout原样输出，这是标准的输入输出操作。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf04", type: "choice", difficulty: 2, question: "下面C++代码执行后将输出10。（ ）\n<pre><code>int N = 0;\nfor (int i = 0; i < 10; i++){\n    continue;\n    N += 1;\n}\ncout << N;</code></pre>", options: ["正确", "错误"], answer: 1, explanation: "continue跳过N+=1，N始终为0，输出0不是10。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf05", type: "choice", difficulty: 2, question: "下面C++代码执行后将输出100。（ ）\n<pre><code>int i;\nfor (i = 0; i <= 100; i++)\n    continue;\ncout << i;</code></pre>", options: ["正确", "错误"], answer: 1, explanation: "i最终为101（循环结束时i++使i=101），输出101不是100。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf06", type: "choice", difficulty: 2, question: "下面C++代码被执行时，将执行三次输出（即cout将被执行3次）。（ ）\n<pre><code>for (int i = 0; i < 10; i += 3)\n    cout << i;</code></pre>", options: ["正确", "错误"], answer: 1, explanation: "i=0,3,6,9时执行，共4次输出，不是3次。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf07", type: "choice", difficulty: 2, question: "C++语句cout << (3,2)执行后，将输出3和2，且3和2之间有逗号间隔。（ ）", options: ["正确", "错误"], answer: 1, explanation: "(3,2)是逗号表达式，值为2。只输出2。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf09", type: "choice", difficulty: 3, question: "在C++中，对浮点变量float f，语句cin >> f; cout << (f<1);在输入是2e-1时，输出是0。（ ）", options: ["正确", "错误"], answer: 1, explanation: "2e-1=0.2, 0.2<1为true, 输出1不是0。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "r2412_tf10", type: "choice", difficulty: 2, question: "在C++的循环体内部，如果break和continue语句连续在一起，那么作用抵消，可以顺利执行下一次循环。（ ）", options: ["正确", "错误"], answer: 1, explanation: "break先执行会直接跳出循环，continue根本不会被执行。", source: "2024_12", examDate: "2024年12月", isJudge: true },
    { id: "real_prog_2412_01", type: "coding", difficulty: 2, question: "温度转换：给定开尔文温度K，计算摄氏温度C和华氏温度F。公式：C = K - 273.15，F = 32 + C * 1.8。如果F高于212度，输出\"Temperature is too high!\"，否则输出C和F（保留两位小数）。\n<p>输入：一个实数K</p>\n<p>样例输入1：<code>412.00</code> 样例输出1：<code>Temperature is too high!</code></p>\n<p>样例输入2：<code>173.56</code> 样例输出2：<code>-99.59 -147.26</code></p>", starterCode: "#include <cstdio>\nusing namespace std;\nint main() {\n    double K;\n    scanf(\"%lf\", &K);\n    // 计算并输出\n    \n    return 0;\n}", testCases: [{ input: "412.00", expectedOutput: "Temperature is too high!", description: "F=286.12>212" }, { input: "173.56", expectedOutput: "-99.59 -147.26", description: "正常输出" }], referenceCode: "#include <cstdio>\nusing namespace std;\nint main() {\n    double K; scanf(\"%lf\", &K);\n    double C = K - 273.15;\n    double F = 32 + C * 1.8;\n    if (F > 212)\n        printf(\"Temperature is too high!\\n\");\n    else\n        printf(\"%.2f %.2f\\n\", C, F);\n    return 0;\n}", explanation: "按公式计算，判断华氏温度是否超过212度。", source: "2024_12", examDate: "2024年12月" },
    { id: "real_prog_2412_02", type: "coding", difficulty: 2, question: "奇数和偶数：小杨有N个正整数，他想知道其中奇数和偶数各有多少个。\n<p>输入第1行：正整数N。之后N行每行一个正整数。</p>\n<p>输出：两个正整数（空格间隔），奇数个数和偶数个数</p>\n<p>样例输入：<code>5\\n1\\n2\\n3\\n4\\n5</code></p>\n<p>样例输出：<code>3 2</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // 统计奇数和偶数\n    \n    return 0;\n}", testCases: [{ input: "5\n1\n2\n3\n4\n5", expectedOutput: "3 2", description: "奇数1,3,5共3个，偶数2,4共2个" }], referenceCode: "#include <iostream>\nusing namespace std;\nint main() {\n    int n, a = 0, b = 0;\n    cin >> n;\n    for (int i = 1; i <= n; i++) {\n        int x; cin >> x;\n        if (x % 2 != 0) a++;\n        else b++;\n    }\n    cout << a << \" \" << b << endl;\n    return 0;\n}", explanation: "遍历输入，用%2判断奇偶分别计数。", source: "2024_12", examDate: "2024年12月" },

    // ===== 2025年03月 真题补充 =====
    { id: "r2503_q05", type: "choice", difficulty: 3, question: "下面框架在L1和L2处填写选项中的代码，哪组不能通过编译（ ）。\n<pre><code>int main() {\n    int i = 0;\n    __________ // L1\n    break;\n    __________ // L2\n    return 0;\n}</code></pre>", options: ["do { ... } while (i != 0);", "for (; i < 10; i++) { ... }", "if (i == 0) { ... }", "switch (i) { ... }"], answer: 2, explanation: "break只能在循环(for/while/do-while)和switch中使用，在if中使用会编译错误。", source: "2025_03", examDate: "2025年3月" },
    { id: "r2503_q07", type: "choice", difficulty: 2, question: "有关下列C++代码的说法，错误的是( )。\n<pre><code>printf(\"我爱码代码！\");</code></pre>", options: ["双引号内汉字改为英文Hello能正确执行", "双引号内汉字改为Hello代码！能正确执行", "每个双引号都可以改为两个单引号", "每个双引号都可以改为三个双引号"], answer: 2, explanation: "两个单引号''是多字符字面量，不能替代双引号作为字符串。", source: "2025_03", examDate: "2025年3月" },
    { id: "r2503_q13", type: "choice", difficulty: 2, question: "下面C++代码执行后输出是（ ）。\n<pre><code>int tnt = 0;\nfor (int i = -1000; i < 1000; i++)\n    tnt += i;\ncout << tnt << endl;</code></pre>", options: ["-1000", "0", "999", "1000"], answer: 0, explanation: "-1000到999求和：正负数相互抵消(-999+999=0等)，只剩-1000。", source: "2025_03", examDate: "2025年3月" },
    { id: "r2503_q14", type: "choice", difficulty: 3, question: "下面C++代码执行后输出的是（ ）。\n<pre><code>int i;\nfor (i = 1; i < 100; i += 5)\n    continue;\ncout << i << endl;</code></pre>", options: ["101", "100", "99", "96"], answer: 0, explanation: "i=1,6,11,...,96。96<100进入循环,i+=5→101。101<100为false退出,输出101。", source: "2025_03", examDate: "2025年3月" },
    { id: "r2503_tf01", type: "choice", difficulty: 1, question: "C++、Python都是高级编程语言，它们的每条语句最终都要通过机器指令来完成。（ ）", options: ["正确", "错误"], answer: 0, explanation: "高级语言最终都要编译或解释为机器指令执行。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "r2503_tf03", type: "choice", difficulty: 2, question: "执行如下C++代码如果在键盘上输入10，执行后将输出20。（ ）\n<pre><code>char N;\nprintf(\"请输入正整数：\");\ncin >> N;\nprintf(\"%d\\n\", N * 2);</code></pre>", options: ["正确", "错误"], answer: 1, explanation: "char N读入字符'1'(ASCII 49)，N*2=98，不是20。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "r2503_tf04", type: "choice", difficulty: 2, question: "删除下面C++代码中的continue不影响程序的执行效果。（ ）\n<pre><code>for (int i = 0; i < 100; i++){\n    if (i % 2 == 0){\n        printf(\"偶数\");\n        continue;\n    }\n    else\n        printf(\"奇数\");\n}</code></pre>", options: ["正确", "错误"], answer: 0, explanation: "if-else结构本身互斥，continue在此处是多余的，删除不影响结果。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "r2503_tf08", type: "choice", difficulty: 2, question: "在C++代码中，user_Name、_userName、user-Name、userName_ 都是合法的变量名。（ ）", options: ["正确", "错误"], answer: 1, explanation: "user-Name含连字符，不是合法变量名。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "r2503_tf09", type: "choice", difficulty: 1, question: "C++语言中continue语句可以用来提前结束循环。（ ）", options: ["正确", "错误"], answer: 1, explanation: "break结束循环，continue只是跳过当前迭代继续下一次。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "r2503_tf10", type: "choice", difficulty: 2, question: "C++中定义整型变量N，执行语句scanf(\"%d\", &N); cout << N / 3 * 5;时输入3.6，则输出是6。（ ）", options: ["正确", "错误"], answer: 1, explanation: "scanf读入3，N=3。3/3*5=1*5=5，不是6。", source: "2025_03", examDate: "2025年3月", isJudge: true },
    { id: "real_prog_2503_02", type: "coding", difficulty: 2, question: "四舍五入：给定N个整数，将每个整数四舍五入到最接近的整十数。例如43→40，58→60。\n<p>输入第1行：整数个数N。接下来N行每行一个整数X。</p>\n<p>输出：N行，每行四舍五入后的结果</p>\n<p>样例输入：<code>5\\n43\\n58\\n25\\n67\\n90</code></p>\n<p>样例输出：<code>40\\n60\\n30\\n70\\n90</code></p>", starterCode: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        int x;\n        cin >> x;\n        // 四舍五入到整十\n        \n    }\n    return 0;\n}", testCases: [{ input: "5\n43\n58\n25\n67\n90", expectedOutput: "40\n60\n30\n70\n90", description: "四舍五入到整十" }], referenceCode: "#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    for (int i = 1, x; i <= n; i++) {\n        cin >> x;\n        cout << (x + 5) / 10 * 10 << endl;\n    }\n    return 0;\n}", explanation: "(x+5)/10*10实现四舍五入到整十：先加5再整除10再乘10。", source: "2025_03", examDate: "2025年3月" }

  ]
};

